// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/pb/bolg.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameRule int32

const (
	GameRule_UNSET    GameRule = 0
	GameRule_SURVIVAL GameRule = 1
)

var GameRule_name = map[int32]string{
	0: "UNSET",
	1: "SURVIVAL",
}

var GameRule_value = map[string]int32{
	"UNSET":    0,
	"SURVIVAL": 1,
}

func (x GameRule) String() string {
	return proto.EnumName(GameRule_name, int32(x))
}

func (GameRule) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{0}
}

type RoomMessage struct {
	// Types that are valid to be assigned to Data:
	//	*RoomMessage_CreateAndJoinRoomReq
	//	*RoomMessage_CreateAndJoinRoomResp
	//	*RoomMessage_JoinRoomReq
	//	*RoomMessage_JoinRoomResp
	//	*RoomMessage_JoinRoomMsg
	Data                 isRoomMessage_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RoomMessage) Reset()         { *m = RoomMessage{} }
func (m *RoomMessage) String() string { return proto.CompactTextString(m) }
func (*RoomMessage) ProtoMessage()    {}
func (*RoomMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{0}
}

func (m *RoomMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMessage.Unmarshal(m, b)
}
func (m *RoomMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMessage.Marshal(b, m, deterministic)
}
func (m *RoomMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMessage.Merge(m, src)
}
func (m *RoomMessage) XXX_Size() int {
	return xxx_messageInfo_RoomMessage.Size(m)
}
func (m *RoomMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMessage proto.InternalMessageInfo

type isRoomMessage_Data interface {
	isRoomMessage_Data()
}

type RoomMessage_CreateAndJoinRoomReq struct {
	CreateAndJoinRoomReq *CreateAndJoinRoomRequest `protobuf:"bytes,1,opt,name=create_and_join_room_req,json=createAndJoinRoomReq,proto3,oneof"`
}

type RoomMessage_CreateAndJoinRoomResp struct {
	CreateAndJoinRoomResp *CreateAndJoinRoomResponse `protobuf:"bytes,2,opt,name=create_and_join_room_resp,json=createAndJoinRoomResp,proto3,oneof"`
}

type RoomMessage_JoinRoomReq struct {
	JoinRoomReq *JoinRoomRequest `protobuf:"bytes,3,opt,name=join_room_req,json=joinRoomReq,proto3,oneof"`
}

type RoomMessage_JoinRoomResp struct {
	JoinRoomResp *JoinRoomResponse `protobuf:"bytes,4,opt,name=join_room_resp,json=joinRoomResp,proto3,oneof"`
}

type RoomMessage_JoinRoomMsg struct {
	JoinRoomMsg *JoinRoomMessage `protobuf:"bytes,5,opt,name=join_room_msg,json=joinRoomMsg,proto3,oneof"`
}

func (*RoomMessage_CreateAndJoinRoomReq) isRoomMessage_Data() {}

func (*RoomMessage_CreateAndJoinRoomResp) isRoomMessage_Data() {}

func (*RoomMessage_JoinRoomReq) isRoomMessage_Data() {}

func (*RoomMessage_JoinRoomResp) isRoomMessage_Data() {}

func (*RoomMessage_JoinRoomMsg) isRoomMessage_Data() {}

func (m *RoomMessage) GetData() isRoomMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RoomMessage) GetCreateAndJoinRoomReq() *CreateAndJoinRoomRequest {
	if x, ok := m.GetData().(*RoomMessage_CreateAndJoinRoomReq); ok {
		return x.CreateAndJoinRoomReq
	}
	return nil
}

func (m *RoomMessage) GetCreateAndJoinRoomResp() *CreateAndJoinRoomResponse {
	if x, ok := m.GetData().(*RoomMessage_CreateAndJoinRoomResp); ok {
		return x.CreateAndJoinRoomResp
	}
	return nil
}

func (m *RoomMessage) GetJoinRoomReq() *JoinRoomRequest {
	if x, ok := m.GetData().(*RoomMessage_JoinRoomReq); ok {
		return x.JoinRoomReq
	}
	return nil
}

func (m *RoomMessage) GetJoinRoomResp() *JoinRoomResponse {
	if x, ok := m.GetData().(*RoomMessage_JoinRoomResp); ok {
		return x.JoinRoomResp
	}
	return nil
}

func (m *RoomMessage) GetJoinRoomMsg() *JoinRoomMessage {
	if x, ok := m.GetData().(*RoomMessage_JoinRoomMsg); ok {
		return x.JoinRoomMsg
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RoomMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RoomMessage_CreateAndJoinRoomReq)(nil),
		(*RoomMessage_CreateAndJoinRoomResp)(nil),
		(*RoomMessage_JoinRoomReq)(nil),
		(*RoomMessage_JoinRoomResp)(nil),
		(*RoomMessage_JoinRoomMsg)(nil),
	}
}

type CreateAndJoinRoomRequest struct {
	// 注意！: このフィールドは認証処理が実装され次第消えます。
	PlayerName           string   `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAndJoinRoomRequest) Reset()         { *m = CreateAndJoinRoomRequest{} }
func (m *CreateAndJoinRoomRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAndJoinRoomRequest) ProtoMessage()    {}
func (*CreateAndJoinRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{1}
}

func (m *CreateAndJoinRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAndJoinRoomRequest.Unmarshal(m, b)
}
func (m *CreateAndJoinRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAndJoinRoomRequest.Marshal(b, m, deterministic)
}
func (m *CreateAndJoinRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAndJoinRoomRequest.Merge(m, src)
}
func (m *CreateAndJoinRoomRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAndJoinRoomRequest.Size(m)
}
func (m *CreateAndJoinRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAndJoinRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAndJoinRoomRequest proto.InternalMessageInfo

func (m *CreateAndJoinRoomRequest) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

type CreateAndJoinRoomResponse struct {
	Room                 *Room    `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAndJoinRoomResponse) Reset()         { *m = CreateAndJoinRoomResponse{} }
func (m *CreateAndJoinRoomResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAndJoinRoomResponse) ProtoMessage()    {}
func (*CreateAndJoinRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{2}
}

func (m *CreateAndJoinRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAndJoinRoomResponse.Unmarshal(m, b)
}
func (m *CreateAndJoinRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAndJoinRoomResponse.Marshal(b, m, deterministic)
}
func (m *CreateAndJoinRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAndJoinRoomResponse.Merge(m, src)
}
func (m *CreateAndJoinRoomResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAndJoinRoomResponse.Size(m)
}
func (m *CreateAndJoinRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAndJoinRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAndJoinRoomResponse proto.InternalMessageInfo

func (m *CreateAndJoinRoomResponse) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

type JoinRoomRequest struct {
	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 注意！: このフィールドは認証処理が実装され次第消えます。
	PlayerName           string   `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomRequest) Reset()         { *m = JoinRoomRequest{} }
func (m *JoinRoomRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRoomRequest) ProtoMessage()    {}
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{3}
}

func (m *JoinRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomRequest.Unmarshal(m, b)
}
func (m *JoinRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomRequest.Marshal(b, m, deterministic)
}
func (m *JoinRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomRequest.Merge(m, src)
}
func (m *JoinRoomRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRoomRequest.Size(m)
}
func (m *JoinRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomRequest proto.InternalMessageInfo

func (m *JoinRoomRequest) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *JoinRoomRequest) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

type JoinRoomResponse struct {
	Room                 *Room    `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomResponse) Reset()         { *m = JoinRoomResponse{} }
func (m *JoinRoomResponse) String() string { return proto.CompactTextString(m) }
func (*JoinRoomResponse) ProtoMessage()    {}
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{4}
}

func (m *JoinRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomResponse.Unmarshal(m, b)
}
func (m *JoinRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomResponse.Marshal(b, m, deterministic)
}
func (m *JoinRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomResponse.Merge(m, src)
}
func (m *JoinRoomResponse) XXX_Size() int {
	return xxx_messageInfo_JoinRoomResponse.Size(m)
}
func (m *JoinRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomResponse proto.InternalMessageInfo

func (m *JoinRoomResponse) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

// JoinRoomMessageは実際にJoinRoomRequestをリクエストしたプレイヤー以外に送信されるメッセージです。
type JoinRoomMessage struct {
	// playerは入室してきたプレイヤーです。
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomMessage) Reset()         { *m = JoinRoomMessage{} }
func (m *JoinRoomMessage) String() string { return proto.CompactTextString(m) }
func (*JoinRoomMessage) ProtoMessage()    {}
func (*JoinRoomMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{5}
}

func (m *JoinRoomMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomMessage.Unmarshal(m, b)
}
func (m *JoinRoomMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomMessage.Marshal(b, m, deterministic)
}
func (m *JoinRoomMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomMessage.Merge(m, src)
}
func (m *JoinRoomMessage) XXX_Size() int {
	return xxx_messageInfo_JoinRoomMessage.Size(m)
}
func (m *JoinRoomMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomMessage.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomMessage proto.InternalMessageInfo

func (m *JoinRoomMessage) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type Room struct {
	// output only
	// idはルーム番号にも利用されます。
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// output only
	GameRule GameRule `protobuf:"varint,2,opt,name=game_rule,json=gameRule,proto3,enum=bolg.GameRule" json:"game_rule,omitempty"`
	// output only
	Players []*Player `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	// output only
	GameStart bool `protobuf:"varint,4,opt,name=game_start,json=gameStart,proto3" json:"game_start,omitempty"`
	// output only
	// owner_idはルームオーナーとなるプレイヤーのIDです。
	// 値が0の場合、オーナーが存在しないことを意味します。
	OwnerId              int64    `protobuf:"varint,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{6}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Room) GetGameRule() GameRule {
	if m != nil {
		return m.GameRule
	}
	return GameRule_UNSET
}

func (m *Room) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Room) GetGameStart() bool {
	if m != nil {
		return m.GameStart
	}
	return false
}

func (m *Room) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type Player struct {
	// output only
	// idは赤外線信号にも利用されます。
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// nameはUserのnameと同じです。
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// output only
	Hp int64 `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	// output only
	// readyはゲームを行うための準備ができたかどうかを表します。
	// ルーム内のすべてのプレイヤーのreadyがtrueになったとき、
	// ゲームを開始することができます。
	Ready                bool     `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{7}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetHp() int64 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *Player) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

func init() {
	proto.RegisterEnum("bolg.GameRule", GameRule_name, GameRule_value)
	proto.RegisterType((*RoomMessage)(nil), "bolg.RoomMessage")
	proto.RegisterType((*CreateAndJoinRoomRequest)(nil), "bolg.CreateAndJoinRoomRequest")
	proto.RegisterType((*CreateAndJoinRoomResponse)(nil), "bolg.CreateAndJoinRoomResponse")
	proto.RegisterType((*JoinRoomRequest)(nil), "bolg.JoinRoomRequest")
	proto.RegisterType((*JoinRoomResponse)(nil), "bolg.JoinRoomResponse")
	proto.RegisterType((*JoinRoomMessage)(nil), "bolg.JoinRoomMessage")
	proto.RegisterType((*Room)(nil), "bolg.Room")
	proto.RegisterType((*Player)(nil), "bolg.Player")
}

func init() { proto.RegisterFile("server/pb/bolg.proto", fileDescriptor_598f3ef7b8dd4d09) }

var fileDescriptor_598f3ef7b8dd4d09 = []byte{
	// 573 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0xe3, 0xd8, 0x39, 0x4d, 0xfa, 0xe5, 0x2b, 0xab, 0x16, 0x5c, 0x24, 0xda, 0xca, 0x20,
	0x54, 0x81, 0x48, 0x50, 0x10, 0xea, 0x45, 0x24, 0xa4, 0xa6, 0x20, 0x1a, 0xa0, 0x55, 0xb4, 0xa1,
	0x15, 0x82, 0x0b, 0xb3, 0xb1, 0x47, 0x8e, 0x23, 0xdb, 0xeb, 0xee, 0x3a, 0x81, 0xbe, 0x00, 0x6f,
	0xc2, 0x7b, 0x22, 0xaf, 0x9d, 0x03, 0x39, 0x5c, 0x70, 0xb7, 0x73, 0xfa, 0xcf, 0x6f, 0x67, 0x57,
	0x03, 0x7b, 0x12, 0xc5, 0x14, 0x45, 0x2b, 0x1e, 0xb6, 0x86, 0x3c, 0xf0, 0x9a, 0xb1, 0xe0, 0x09,
	0x27, 0x46, 0x7a, 0xb6, 0x7e, 0xe9, 0x50, 0xa7, 0x9c, 0x87, 0x97, 0x28, 0x25, 0xf3, 0x90, 0x7c,
	0x01, 0xd3, 0x11, 0xc8, 0x12, 0xb4, 0x59, 0xe4, 0xda, 0x63, 0xee, 0x47, 0xb6, 0xe0, 0x3c, 0xb4,
	0x05, 0xde, 0x9a, 0xda, 0xb1, 0x76, 0x52, 0x6f, 0x1f, 0x36, 0x95, 0xc8, 0xb9, 0xca, 0x3a, 0x8b,
	0xdc, 0x0f, 0xdc, 0x8f, 0x52, 0x05, 0x8a, 0xb7, 0x13, 0x94, 0xc9, 0x45, 0x81, 0xee, 0x39, 0x1b,
	0x62, 0xe4, 0x1b, 0x1c, 0x6c, 0x51, 0x96, 0xb1, 0x59, 0x54, 0xd2, 0x47, 0x5b, 0xa5, 0x65, 0xcc,
	0x23, 0x89, 0x17, 0x05, 0xba, 0xef, 0x6c, 0x0a, 0x92, 0x0e, 0xfc, 0xf7, 0x37, 0xab, 0xae, 0x04,
	0xf7, 0x33, 0xc1, 0x75, 0xc4, 0xfa, 0x78, 0x89, 0xec, 0x0d, 0x34, 0x56, 0x70, 0x0c, 0x55, 0x7d,
	0x7f, 0xb5, 0x7a, 0x4e, 0xb1, 0x33, 0xde, 0xda, 0x3c, 0x94, 0x9e, 0x59, 0xda, 0xd4, 0x3c, 0x9f,
	0xf0, 0x72, 0xf3, 0x4b, 0xe9, 0x75, 0xcb, 0x60, 0xb8, 0x2c, 0x61, 0x56, 0x07, 0xcc, 0x6d, 0x23,
	0x25, 0x47, 0x50, 0x8f, 0x03, 0x76, 0x87, 0xc2, 0x8e, 0x58, 0x88, 0xea, 0x1d, 0x6a, 0x14, 0x32,
	0xd7, 0x15, 0x0b, 0xd1, 0xea, 0xc0, 0xc1, 0xd6, 0xa1, 0x91, 0x43, 0x30, 0x52, 0xb2, 0xfc, 0xf9,
	0x20, 0xa3, 0x52, 0x19, 0xca, 0x6f, 0x7d, 0x84, 0xff, 0x57, 0x1b, 0x3e, 0x80, 0x8a, 0xba, 0x8c,
	0xef, 0xaa, 0x2a, 0x9d, 0x96, 0x53, 0xb3, 0xe7, 0xae, 0x92, 0x14, 0xd7, 0x48, 0xda, 0xb0, 0xfb,
	0xcf, 0x00, 0xa7, 0x0b, 0x80, 0xd9, 0x37, 0x7c, 0x02, 0xe5, 0x4c, 0x34, 0x2f, 0xda, 0xc9, 0x8a,
	0xfa, 0xca, 0x47, 0xf3, 0x98, 0xf5, 0x5b, 0x03, 0x23, 0xad, 0x22, 0x0d, 0x28, 0xce, 0x51, 0x8b,
	0xbe, 0x4b, 0x9e, 0x43, 0xcd, 0x63, 0x21, 0xda, 0x62, 0x12, 0x64, 0x90, 0x8d, 0x76, 0x23, 0x53,
	0x78, 0xcf, 0x42, 0xa4, 0x93, 0x00, 0x69, 0xd5, 0xcb, 0x4f, 0xe4, 0x29, 0x54, 0x32, 0x3d, 0x69,
	0xea, 0xc7, 0xfa, 0x5a, 0xb3, 0x59, 0x90, 0x3c, 0x02, 0x50, 0xa2, 0x32, 0x61, 0x22, 0x51, 0x5f,
	0xa4, 0x4a, 0x55, 0x9b, 0x41, 0xea, 0x20, 0x07, 0x50, 0xe5, 0x3f, 0x22, 0x14, 0xe9, 0xd0, 0x4a,
	0x8a, 0xa4, 0xa2, 0xec, 0x9e, 0x6b, 0x51, 0x28, 0x67, 0x62, 0x6b, 0xa0, 0x04, 0x8c, 0xa5, 0x41,
	0xaa, 0x73, 0x9a, 0x33, 0x8a, 0xd5, 0x07, 0xd6, 0x69, 0x71, 0x14, 0x93, 0x3d, 0x28, 0x09, 0x64,
	0xee, 0x5d, 0xde, 0x32, 0x33, 0x9e, 0x3d, 0x86, 0xea, 0xec, 0x2e, 0xa4, 0x06, 0xa5, 0xeb, 0xab,
	0xc1, 0xbb, 0xcf, 0xbb, 0x05, 0xb2, 0x03, 0xd5, 0xc1, 0x35, 0xbd, 0xe9, 0xdd, 0x9c, 0x7d, 0xda,
	0xd5, 0xda, 0x6f, 0xa1, 0xde, 0xe5, 0x81, 0x37, 0x40, 0x31, 0xf5, 0x1d, 0x24, 0xaf, 0xa1, 0x72,
	0xce, 0xa3, 0x08, 0x9d, 0x84, 0xdc, 0x5b, 0xbc, 0x42, 0x3e, 0xf3, 0x87, 0xeb, 0x2e, 0xab, 0x70,
	0xa2, 0xbd, 0xd4, 0xba, 0xdf, 0xc1, 0xe4, 0xc2, 0x53, 0x51, 0xdb, 0xc5, 0x29, 0x06, 0x3c, 0x46,
	0x21, 0x95, 0xdd, 0xad, 0xa5, 0xfa, 0xfd, 0x74, 0xa1, 0xf4, 0xb5, 0xaf, 0xa7, 0x9e, 0x9f, 0x8c,
	0x26, 0xc3, 0xa6, 0xc3, 0x43, 0xb5, 0x69, 0x5e, 0x2c, 0xb2, 0x5b, 0x3f, 0x5b, 0xb1, 0xe0, 0x63,
	0x74, 0x12, 0xa9, 0x42, 0xad, 0xf9, 0x4e, 0xea, 0xc4, 0xc3, 0x61, 0x59, 0xad, 0xa4, 0x57, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xef, 0x72, 0x21, 0xa0, 0xaa, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BolgServiceClient is the client API for BolgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BolgServiceClient interface {
	// ConnectはRoom Messagingを行うためのRPCです。
	Connect(ctx context.Context, opts ...grpc.CallOption) (BolgService_ConnectClient, error)
}

type bolgServiceClient struct {
	cc *grpc.ClientConn
}

func NewBolgServiceClient(cc *grpc.ClientConn) BolgServiceClient {
	return &bolgServiceClient{cc}
}

func (c *bolgServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (BolgService_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BolgService_serviceDesc.Streams[0], "/bolg.BolgService/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &bolgServiceConnectClient{stream}
	return x, nil
}

type BolgService_ConnectClient interface {
	Send(*RoomMessage) error
	Recv() (*RoomMessage, error)
	grpc.ClientStream
}

type bolgServiceConnectClient struct {
	grpc.ClientStream
}

func (x *bolgServiceConnectClient) Send(m *RoomMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bolgServiceConnectClient) Recv() (*RoomMessage, error) {
	m := new(RoomMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BolgServiceServer is the server API for BolgService service.
type BolgServiceServer interface {
	// ConnectはRoom Messagingを行うためのRPCです。
	Connect(BolgService_ConnectServer) error
}

func RegisterBolgServiceServer(s *grpc.Server, srv BolgServiceServer) {
	s.RegisterService(&_BolgService_serviceDesc, srv)
}

func _BolgService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BolgServiceServer).Connect(&bolgServiceConnectServer{stream})
}

type BolgService_ConnectServer interface {
	Send(*RoomMessage) error
	Recv() (*RoomMessage, error)
	grpc.ServerStream
}

type bolgServiceConnectServer struct {
	grpc.ServerStream
}

func (x *bolgServiceConnectServer) Send(m *RoomMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bolgServiceConnectServer) Recv() (*RoomMessage, error) {
	m := new(RoomMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BolgService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bolg.BolgService",
	HandlerType: (*BolgServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _BolgService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server/pb/bolg.proto",
}
