// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/pb/bolg.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameRule int32

const (
	GameRule_UNSET    GameRule = 0
	GameRule_SURVIVAL GameRule = 1
)

var GameRule_name = map[int32]string{
	0: "UNSET",
	1: "SURVIVAL",
}

var GameRule_value = map[string]int32{
	"UNSET":    0,
	"SURVIVAL": 1,
}

func (x GameRule) String() string {
	return proto.EnumName(GameRule_name, int32(x))
}

func (GameRule) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{0}
}

type RoomMessage struct {
	// Types that are valid to be assigned to Data:
	//	*RoomMessage_CreateAndJoinRoomReq
	//	*RoomMessage_CreateAndJoinRoomResp
	//	*RoomMessage_JoinRoomReq
	//	*RoomMessage_JoinRoomResp
	//	*RoomMessage_JoinRoomMsg
	//	*RoomMessage_NotifyReceivingReq
	//	*RoomMessage_NotifyReceivingMsg
	//	*RoomMessage_SurvivalResultMsg
	//	*RoomMessage_StartGameReq
	//	*RoomMessage_StartGameMsg
	//	*RoomMessage_UpdateWeaponReq
	//	*RoomMessage_UpdateWeaponResp
	//	*RoomMessage_ReadyReq
	//	*RoomMessage_ReadyMsg
	Data                 isRoomMessage_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RoomMessage) Reset()         { *m = RoomMessage{} }
func (m *RoomMessage) String() string { return proto.CompactTextString(m) }
func (*RoomMessage) ProtoMessage()    {}
func (*RoomMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{0}
}

func (m *RoomMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMessage.Unmarshal(m, b)
}
func (m *RoomMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMessage.Marshal(b, m, deterministic)
}
func (m *RoomMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMessage.Merge(m, src)
}
func (m *RoomMessage) XXX_Size() int {
	return xxx_messageInfo_RoomMessage.Size(m)
}
func (m *RoomMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMessage proto.InternalMessageInfo

type isRoomMessage_Data interface {
	isRoomMessage_Data()
}

type RoomMessage_CreateAndJoinRoomReq struct {
	CreateAndJoinRoomReq *CreateAndJoinRoomRequest `protobuf:"bytes,1,opt,name=create_and_join_room_req,json=createAndJoinRoomReq,proto3,oneof"`
}

type RoomMessage_CreateAndJoinRoomResp struct {
	CreateAndJoinRoomResp *CreateAndJoinRoomResponse `protobuf:"bytes,2,opt,name=create_and_join_room_resp,json=createAndJoinRoomResp,proto3,oneof"`
}

type RoomMessage_JoinRoomReq struct {
	JoinRoomReq *JoinRoomRequest `protobuf:"bytes,3,opt,name=join_room_req,json=joinRoomReq,proto3,oneof"`
}

type RoomMessage_JoinRoomResp struct {
	JoinRoomResp *JoinRoomResponse `protobuf:"bytes,4,opt,name=join_room_resp,json=joinRoomResp,proto3,oneof"`
}

type RoomMessage_JoinRoomMsg struct {
	JoinRoomMsg *JoinRoomMessage `protobuf:"bytes,5,opt,name=join_room_msg,json=joinRoomMsg,proto3,oneof"`
}

type RoomMessage_NotifyReceivingReq struct {
	NotifyReceivingReq *NotifyReceivingRequest `protobuf:"bytes,6,opt,name=notify_receiving_req,json=notifyReceivingReq,proto3,oneof"`
}

type RoomMessage_NotifyReceivingMsg struct {
	NotifyReceivingMsg *NotifyReceivingMessage `protobuf:"bytes,7,opt,name=notify_receiving_msg,json=notifyReceivingMsg,proto3,oneof"`
}

type RoomMessage_SurvivalResultMsg struct {
	SurvivalResultMsg *SurvivalResultMessage `protobuf:"bytes,8,opt,name=survival_result_msg,json=survivalResultMsg,proto3,oneof"`
}

type RoomMessage_StartGameReq struct {
	StartGameReq *StartGameRequest `protobuf:"bytes,9,opt,name=start_game_req,json=startGameReq,proto3,oneof"`
}

type RoomMessage_StartGameMsg struct {
	StartGameMsg *StartGameMessage `protobuf:"bytes,10,opt,name=start_game_msg,json=startGameMsg,proto3,oneof"`
}

type RoomMessage_UpdateWeaponReq struct {
	UpdateWeaponReq *UpdateWeaponRequest `protobuf:"bytes,11,opt,name=update_weapon_req,json=updateWeaponReq,proto3,oneof"`
}

type RoomMessage_UpdateWeaponResp struct {
	UpdateWeaponResp *UpdateWeaponResponse `protobuf:"bytes,12,opt,name=update_weapon_resp,json=updateWeaponResp,proto3,oneof"`
}

type RoomMessage_ReadyReq struct {
	ReadyReq *ReadyRequest `protobuf:"bytes,13,opt,name=ready_req,json=readyReq,proto3,oneof"`
}

type RoomMessage_ReadyMsg struct {
	ReadyMsg *ReadyMessage `protobuf:"bytes,14,opt,name=ready_msg,json=readyMsg,proto3,oneof"`
}

func (*RoomMessage_CreateAndJoinRoomReq) isRoomMessage_Data() {}

func (*RoomMessage_CreateAndJoinRoomResp) isRoomMessage_Data() {}

func (*RoomMessage_JoinRoomReq) isRoomMessage_Data() {}

func (*RoomMessage_JoinRoomResp) isRoomMessage_Data() {}

func (*RoomMessage_JoinRoomMsg) isRoomMessage_Data() {}

func (*RoomMessage_NotifyReceivingReq) isRoomMessage_Data() {}

func (*RoomMessage_NotifyReceivingMsg) isRoomMessage_Data() {}

func (*RoomMessage_SurvivalResultMsg) isRoomMessage_Data() {}

func (*RoomMessage_StartGameReq) isRoomMessage_Data() {}

func (*RoomMessage_StartGameMsg) isRoomMessage_Data() {}

func (*RoomMessage_UpdateWeaponReq) isRoomMessage_Data() {}

func (*RoomMessage_UpdateWeaponResp) isRoomMessage_Data() {}

func (*RoomMessage_ReadyReq) isRoomMessage_Data() {}

func (*RoomMessage_ReadyMsg) isRoomMessage_Data() {}

func (m *RoomMessage) GetData() isRoomMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RoomMessage) GetCreateAndJoinRoomReq() *CreateAndJoinRoomRequest {
	if x, ok := m.GetData().(*RoomMessage_CreateAndJoinRoomReq); ok {
		return x.CreateAndJoinRoomReq
	}
	return nil
}

func (m *RoomMessage) GetCreateAndJoinRoomResp() *CreateAndJoinRoomResponse {
	if x, ok := m.GetData().(*RoomMessage_CreateAndJoinRoomResp); ok {
		return x.CreateAndJoinRoomResp
	}
	return nil
}

func (m *RoomMessage) GetJoinRoomReq() *JoinRoomRequest {
	if x, ok := m.GetData().(*RoomMessage_JoinRoomReq); ok {
		return x.JoinRoomReq
	}
	return nil
}

func (m *RoomMessage) GetJoinRoomResp() *JoinRoomResponse {
	if x, ok := m.GetData().(*RoomMessage_JoinRoomResp); ok {
		return x.JoinRoomResp
	}
	return nil
}

func (m *RoomMessage) GetJoinRoomMsg() *JoinRoomMessage {
	if x, ok := m.GetData().(*RoomMessage_JoinRoomMsg); ok {
		return x.JoinRoomMsg
	}
	return nil
}

func (m *RoomMessage) GetNotifyReceivingReq() *NotifyReceivingRequest {
	if x, ok := m.GetData().(*RoomMessage_NotifyReceivingReq); ok {
		return x.NotifyReceivingReq
	}
	return nil
}

func (m *RoomMessage) GetNotifyReceivingMsg() *NotifyReceivingMessage {
	if x, ok := m.GetData().(*RoomMessage_NotifyReceivingMsg); ok {
		return x.NotifyReceivingMsg
	}
	return nil
}

func (m *RoomMessage) GetSurvivalResultMsg() *SurvivalResultMessage {
	if x, ok := m.GetData().(*RoomMessage_SurvivalResultMsg); ok {
		return x.SurvivalResultMsg
	}
	return nil
}

func (m *RoomMessage) GetStartGameReq() *StartGameRequest {
	if x, ok := m.GetData().(*RoomMessage_StartGameReq); ok {
		return x.StartGameReq
	}
	return nil
}

func (m *RoomMessage) GetStartGameMsg() *StartGameMessage {
	if x, ok := m.GetData().(*RoomMessage_StartGameMsg); ok {
		return x.StartGameMsg
	}
	return nil
}

func (m *RoomMessage) GetUpdateWeaponReq() *UpdateWeaponRequest {
	if x, ok := m.GetData().(*RoomMessage_UpdateWeaponReq); ok {
		return x.UpdateWeaponReq
	}
	return nil
}

func (m *RoomMessage) GetUpdateWeaponResp() *UpdateWeaponResponse {
	if x, ok := m.GetData().(*RoomMessage_UpdateWeaponResp); ok {
		return x.UpdateWeaponResp
	}
	return nil
}

func (m *RoomMessage) GetReadyReq() *ReadyRequest {
	if x, ok := m.GetData().(*RoomMessage_ReadyReq); ok {
		return x.ReadyReq
	}
	return nil
}

func (m *RoomMessage) GetReadyMsg() *ReadyMessage {
	if x, ok := m.GetData().(*RoomMessage_ReadyMsg); ok {
		return x.ReadyMsg
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RoomMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RoomMessage_CreateAndJoinRoomReq)(nil),
		(*RoomMessage_CreateAndJoinRoomResp)(nil),
		(*RoomMessage_JoinRoomReq)(nil),
		(*RoomMessage_JoinRoomResp)(nil),
		(*RoomMessage_JoinRoomMsg)(nil),
		(*RoomMessage_NotifyReceivingReq)(nil),
		(*RoomMessage_NotifyReceivingMsg)(nil),
		(*RoomMessage_SurvivalResultMsg)(nil),
		(*RoomMessage_StartGameReq)(nil),
		(*RoomMessage_StartGameMsg)(nil),
		(*RoomMessage_UpdateWeaponReq)(nil),
		(*RoomMessage_UpdateWeaponResp)(nil),
		(*RoomMessage_ReadyReq)(nil),
		(*RoomMessage_ReadyMsg)(nil),
	}
}

type CreateAndJoinRoomRequest struct {
	// 注意！: このフィールドは認証処理が実装され次第消えます。
	PlayerName           string   `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAndJoinRoomRequest) Reset()         { *m = CreateAndJoinRoomRequest{} }
func (m *CreateAndJoinRoomRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAndJoinRoomRequest) ProtoMessage()    {}
func (*CreateAndJoinRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{1}
}

func (m *CreateAndJoinRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAndJoinRoomRequest.Unmarshal(m, b)
}
func (m *CreateAndJoinRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAndJoinRoomRequest.Marshal(b, m, deterministic)
}
func (m *CreateAndJoinRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAndJoinRoomRequest.Merge(m, src)
}
func (m *CreateAndJoinRoomRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAndJoinRoomRequest.Size(m)
}
func (m *CreateAndJoinRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAndJoinRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAndJoinRoomRequest proto.InternalMessageInfo

func (m *CreateAndJoinRoomRequest) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

type CreateAndJoinRoomResponse struct {
	Room *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	// tokenはクライアントがどのルームの誰なのかを表します。
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAndJoinRoomResponse) Reset()         { *m = CreateAndJoinRoomResponse{} }
func (m *CreateAndJoinRoomResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAndJoinRoomResponse) ProtoMessage()    {}
func (*CreateAndJoinRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{2}
}

func (m *CreateAndJoinRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAndJoinRoomResponse.Unmarshal(m, b)
}
func (m *CreateAndJoinRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAndJoinRoomResponse.Marshal(b, m, deterministic)
}
func (m *CreateAndJoinRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAndJoinRoomResponse.Merge(m, src)
}
func (m *CreateAndJoinRoomResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAndJoinRoomResponse.Size(m)
}
func (m *CreateAndJoinRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAndJoinRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAndJoinRoomResponse proto.InternalMessageInfo

func (m *CreateAndJoinRoomResponse) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *CreateAndJoinRoomResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type JoinRoomRequest struct {
	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 注意！: このフィールドは認証処理が実装され次第消えます。
	PlayerName           string   `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomRequest) Reset()         { *m = JoinRoomRequest{} }
func (m *JoinRoomRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRoomRequest) ProtoMessage()    {}
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{3}
}

func (m *JoinRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomRequest.Unmarshal(m, b)
}
func (m *JoinRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomRequest.Marshal(b, m, deterministic)
}
func (m *JoinRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomRequest.Merge(m, src)
}
func (m *JoinRoomRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRoomRequest.Size(m)
}
func (m *JoinRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomRequest proto.InternalMessageInfo

func (m *JoinRoomRequest) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *JoinRoomRequest) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

type JoinRoomResponse struct {
	Room *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	// tokenはクライアントがどのルームの誰なのかを表します。
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomResponse) Reset()         { *m = JoinRoomResponse{} }
func (m *JoinRoomResponse) String() string { return proto.CompactTextString(m) }
func (*JoinRoomResponse) ProtoMessage()    {}
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{4}
}

func (m *JoinRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomResponse.Unmarshal(m, b)
}
func (m *JoinRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomResponse.Marshal(b, m, deterministic)
}
func (m *JoinRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomResponse.Merge(m, src)
}
func (m *JoinRoomResponse) XXX_Size() int {
	return xxx_messageInfo_JoinRoomResponse.Size(m)
}
func (m *JoinRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomResponse proto.InternalMessageInfo

func (m *JoinRoomResponse) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *JoinRoomResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// JoinRoomMessageは実際にJoinRoomRequestをリクエストしたプレイヤー以外に送信されるメッセージです。
type JoinRoomMessage struct {
	// playerは入室してきたプレイヤーです。
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomMessage) Reset()         { *m = JoinRoomMessage{} }
func (m *JoinRoomMessage) String() string { return proto.CompactTextString(m) }
func (*JoinRoomMessage) ProtoMessage()    {}
func (*JoinRoomMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{5}
}

func (m *JoinRoomMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomMessage.Unmarshal(m, b)
}
func (m *JoinRoomMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomMessage.Marshal(b, m, deterministic)
}
func (m *JoinRoomMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomMessage.Merge(m, src)
}
func (m *JoinRoomMessage) XXX_Size() int {
	return xxx_messageInfo_JoinRoomMessage.Size(m)
}
func (m *JoinRoomMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomMessage.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomMessage proto.InternalMessageInfo

func (m *JoinRoomMessage) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type NotifyReceivingRequest struct {
	// player_idは受信したプレイヤーIDです。
	PlayerId int64 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// tokenはクライアントがどのルームの誰なのかを表します。
	// ルームを入室したときに生成されたtokenをセットしてください。
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyReceivingRequest) Reset()         { *m = NotifyReceivingRequest{} }
func (m *NotifyReceivingRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyReceivingRequest) ProtoMessage()    {}
func (*NotifyReceivingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{6}
}

func (m *NotifyReceivingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyReceivingRequest.Unmarshal(m, b)
}
func (m *NotifyReceivingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyReceivingRequest.Marshal(b, m, deterministic)
}
func (m *NotifyReceivingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyReceivingRequest.Merge(m, src)
}
func (m *NotifyReceivingRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyReceivingRequest.Size(m)
}
func (m *NotifyReceivingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyReceivingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyReceivingRequest proto.InternalMessageInfo

func (m *NotifyReceivingRequest) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *NotifyReceivingRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// NotifyReceivingMessageはNotifyReceivingRequestリクエストされたときに、すべてのプレイヤーに送信されるメッセージです。
type NotifyReceivingMessage struct {
	// playerはダメージを受けたプレイヤーです。
	Player *Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	// killerNameはダメージを受けたプレイヤーを殺したプレイヤーの名前です。
	// ダメージを受けたプレイヤーが死亡していない場合、このフィールドは空文字となります。
	KillerName           string   `protobuf:"bytes,2,opt,name=killerName,proto3" json:"killerName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyReceivingMessage) Reset()         { *m = NotifyReceivingMessage{} }
func (m *NotifyReceivingMessage) String() string { return proto.CompactTextString(m) }
func (*NotifyReceivingMessage) ProtoMessage()    {}
func (*NotifyReceivingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{7}
}

func (m *NotifyReceivingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyReceivingMessage.Unmarshal(m, b)
}
func (m *NotifyReceivingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyReceivingMessage.Marshal(b, m, deterministic)
}
func (m *NotifyReceivingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyReceivingMessage.Merge(m, src)
}
func (m *NotifyReceivingMessage) XXX_Size() int {
	return xxx_messageInfo_NotifyReceivingMessage.Size(m)
}
func (m *NotifyReceivingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyReceivingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyReceivingMessage proto.InternalMessageInfo

func (m *NotifyReceivingMessage) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *NotifyReceivingMessage) GetKillerName() string {
	if m != nil {
		return m.KillerName
	}
	return ""
}

type SurvivalResultMessage struct {
	Winner               *Player                   `protobuf:"bytes,1,opt,name=winner,proto3" json:"winner,omitempty"`
	Personals            []*SurvivalPersonalResult `protobuf:"bytes,2,rep,name=personals,proto3" json:"personals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SurvivalResultMessage) Reset()         { *m = SurvivalResultMessage{} }
func (m *SurvivalResultMessage) String() string { return proto.CompactTextString(m) }
func (*SurvivalResultMessage) ProtoMessage()    {}
func (*SurvivalResultMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{8}
}

func (m *SurvivalResultMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurvivalResultMessage.Unmarshal(m, b)
}
func (m *SurvivalResultMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurvivalResultMessage.Marshal(b, m, deterministic)
}
func (m *SurvivalResultMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurvivalResultMessage.Merge(m, src)
}
func (m *SurvivalResultMessage) XXX_Size() int {
	return xxx_messageInfo_SurvivalResultMessage.Size(m)
}
func (m *SurvivalResultMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SurvivalResultMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SurvivalResultMessage proto.InternalMessageInfo

func (m *SurvivalResultMessage) GetWinner() *Player {
	if m != nil {
		return m.Winner
	}
	return nil
}

func (m *SurvivalResultMessage) GetPersonals() []*SurvivalPersonalResult {
	if m != nil {
		return m.Personals
	}
	return nil
}

type SurvivalPersonalResult struct {
	PlayerName           string   `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	KillCount            int64    `protobuf:"varint,2,opt,name=kill_count,json=killCount,proto3" json:"kill_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SurvivalPersonalResult) Reset()         { *m = SurvivalPersonalResult{} }
func (m *SurvivalPersonalResult) String() string { return proto.CompactTextString(m) }
func (*SurvivalPersonalResult) ProtoMessage()    {}
func (*SurvivalPersonalResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{9}
}

func (m *SurvivalPersonalResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurvivalPersonalResult.Unmarshal(m, b)
}
func (m *SurvivalPersonalResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurvivalPersonalResult.Marshal(b, m, deterministic)
}
func (m *SurvivalPersonalResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurvivalPersonalResult.Merge(m, src)
}
func (m *SurvivalPersonalResult) XXX_Size() int {
	return xxx_messageInfo_SurvivalPersonalResult.Size(m)
}
func (m *SurvivalPersonalResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SurvivalPersonalResult.DiscardUnknown(m)
}

var xxx_messageInfo_SurvivalPersonalResult proto.InternalMessageInfo

func (m *SurvivalPersonalResult) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *SurvivalPersonalResult) GetKillCount() int64 {
	if m != nil {
		return m.KillCount
	}
	return 0
}

type StartGameRequest struct {
	// tokenから得られるプレイヤーIDがルームのオーナーIDと一致しない場合、
	// このリクエストは失敗します。
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartGameRequest) Reset()         { *m = StartGameRequest{} }
func (m *StartGameRequest) String() string { return proto.CompactTextString(m) }
func (*StartGameRequest) ProtoMessage()    {}
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{10}
}

func (m *StartGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameRequest.Unmarshal(m, b)
}
func (m *StartGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameRequest.Marshal(b, m, deterministic)
}
func (m *StartGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameRequest.Merge(m, src)
}
func (m *StartGameRequest) XXX_Size() int {
	return xxx_messageInfo_StartGameRequest.Size(m)
}
func (m *StartGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameRequest proto.InternalMessageInfo

func (m *StartGameRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type StartGameMessage struct {
	Room                 *Room    `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartGameMessage) Reset()         { *m = StartGameMessage{} }
func (m *StartGameMessage) String() string { return proto.CompactTextString(m) }
func (*StartGameMessage) ProtoMessage()    {}
func (*StartGameMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{11}
}

func (m *StartGameMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameMessage.Unmarshal(m, b)
}
func (m *StartGameMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameMessage.Marshal(b, m, deterministic)
}
func (m *StartGameMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameMessage.Merge(m, src)
}
func (m *StartGameMessage) XXX_Size() int {
	return xxx_messageInfo_StartGameMessage.Size(m)
}
func (m *StartGameMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameMessage proto.InternalMessageInfo

func (m *StartGameMessage) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

type UpdateWeaponRequest struct {
	Attack               int64    `protobuf:"varint,1,opt,name=attack,proto3" json:"attack,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateWeaponRequest) Reset()         { *m = UpdateWeaponRequest{} }
func (m *UpdateWeaponRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateWeaponRequest) ProtoMessage()    {}
func (*UpdateWeaponRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{12}
}

func (m *UpdateWeaponRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWeaponRequest.Unmarshal(m, b)
}
func (m *UpdateWeaponRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWeaponRequest.Marshal(b, m, deterministic)
}
func (m *UpdateWeaponRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWeaponRequest.Merge(m, src)
}
func (m *UpdateWeaponRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateWeaponRequest.Size(m)
}
func (m *UpdateWeaponRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWeaponRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWeaponRequest proto.InternalMessageInfo

func (m *UpdateWeaponRequest) GetAttack() int64 {
	if m != nil {
		return m.Attack
	}
	return 0
}

func (m *UpdateWeaponRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UpdateWeaponResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateWeaponResponse) Reset()         { *m = UpdateWeaponResponse{} }
func (m *UpdateWeaponResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateWeaponResponse) ProtoMessage()    {}
func (*UpdateWeaponResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{13}
}

func (m *UpdateWeaponResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWeaponResponse.Unmarshal(m, b)
}
func (m *UpdateWeaponResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWeaponResponse.Marshal(b, m, deterministic)
}
func (m *UpdateWeaponResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWeaponResponse.Merge(m, src)
}
func (m *UpdateWeaponResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateWeaponResponse.Size(m)
}
func (m *UpdateWeaponResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWeaponResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWeaponResponse proto.InternalMessageInfo

type ReadyRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadyRequest) Reset()         { *m = ReadyRequest{} }
func (m *ReadyRequest) String() string { return proto.CompactTextString(m) }
func (*ReadyRequest) ProtoMessage()    {}
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{14}
}

func (m *ReadyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadyRequest.Unmarshal(m, b)
}
func (m *ReadyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadyRequest.Marshal(b, m, deterministic)
}
func (m *ReadyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadyRequest.Merge(m, src)
}
func (m *ReadyRequest) XXX_Size() int {
	return xxx_messageInfo_ReadyRequest.Size(m)
}
func (m *ReadyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadyRequest proto.InternalMessageInfo

func (m *ReadyRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ReadyMessage struct {
	// player_idは準備完了したプレイヤーのIDです。
	PlayerId             int64    `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadyMessage) Reset()         { *m = ReadyMessage{} }
func (m *ReadyMessage) String() string { return proto.CompactTextString(m) }
func (*ReadyMessage) ProtoMessage()    {}
func (*ReadyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{15}
}

func (m *ReadyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadyMessage.Unmarshal(m, b)
}
func (m *ReadyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadyMessage.Marshal(b, m, deterministic)
}
func (m *ReadyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadyMessage.Merge(m, src)
}
func (m *ReadyMessage) XXX_Size() int {
	return xxx_messageInfo_ReadyMessage.Size(m)
}
func (m *ReadyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReadyMessage proto.InternalMessageInfo

func (m *ReadyMessage) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type Room struct {
	// output only
	// idはルーム番号にも利用されます。
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// output only
	GameRule GameRule `protobuf:"varint,2,opt,name=game_rule,json=gameRule,proto3,enum=bolg.GameRule" json:"game_rule,omitempty"`
	// output only
	Players []*Player `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	// output only
	GameStart bool `protobuf:"varint,4,opt,name=game_start,json=gameStart,proto3" json:"game_start,omitempty"`
	// output only
	// owner_idはルームオーナーとなるプレイヤーのIDです。
	// 値が0の場合、オーナーが存在しないことを意味します。
	OwnerId              int64    `protobuf:"varint,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{16}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Room) GetGameRule() GameRule {
	if m != nil {
		return m.GameRule
	}
	return GameRule_UNSET
}

func (m *Room) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Room) GetGameStart() bool {
	if m != nil {
		return m.GameStart
	}
	return false
}

func (m *Room) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type Player struct {
	// output only
	// idは赤外線信号にも利用されます。
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// nameはUserのnameと同じです。
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// output only
	Hp int64 `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	// output only
	// readyはゲームを行うための準備ができたかどうかを表します。
	// ルーム内のすべてのプレイヤーのreadyがtrueになったとき、
	// ゲームを開始することができます。
	Ready                bool     `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_598f3ef7b8dd4d09, []int{17}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetHp() int64 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *Player) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

func init() {
	proto.RegisterEnum("bolg.GameRule", GameRule_name, GameRule_value)
	proto.RegisterType((*RoomMessage)(nil), "bolg.RoomMessage")
	proto.RegisterType((*CreateAndJoinRoomRequest)(nil), "bolg.CreateAndJoinRoomRequest")
	proto.RegisterType((*CreateAndJoinRoomResponse)(nil), "bolg.CreateAndJoinRoomResponse")
	proto.RegisterType((*JoinRoomRequest)(nil), "bolg.JoinRoomRequest")
	proto.RegisterType((*JoinRoomResponse)(nil), "bolg.JoinRoomResponse")
	proto.RegisterType((*JoinRoomMessage)(nil), "bolg.JoinRoomMessage")
	proto.RegisterType((*NotifyReceivingRequest)(nil), "bolg.NotifyReceivingRequest")
	proto.RegisterType((*NotifyReceivingMessage)(nil), "bolg.NotifyReceivingMessage")
	proto.RegisterType((*SurvivalResultMessage)(nil), "bolg.SurvivalResultMessage")
	proto.RegisterType((*SurvivalPersonalResult)(nil), "bolg.SurvivalPersonalResult")
	proto.RegisterType((*StartGameRequest)(nil), "bolg.StartGameRequest")
	proto.RegisterType((*StartGameMessage)(nil), "bolg.StartGameMessage")
	proto.RegisterType((*UpdateWeaponRequest)(nil), "bolg.UpdateWeaponRequest")
	proto.RegisterType((*UpdateWeaponResponse)(nil), "bolg.UpdateWeaponResponse")
	proto.RegisterType((*ReadyRequest)(nil), "bolg.ReadyRequest")
	proto.RegisterType((*ReadyMessage)(nil), "bolg.ReadyMessage")
	proto.RegisterType((*Room)(nil), "bolg.Room")
	proto.RegisterType((*Player)(nil), "bolg.Player")
}

func init() { proto.RegisterFile("server/pb/bolg.proto", fileDescriptor_598f3ef7b8dd4d09) }

var fileDescriptor_598f3ef7b8dd4d09 = []byte{
	// 944 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xff, 0x6e, 0xdb, 0x36,
	0x10, 0xc7, 0xe3, 0x1f, 0xb1, 0xad, 0xb3, 0xeb, 0x3a, 0xac, 0xe3, 0x39, 0xed, 0x96, 0x16, 0x5a,
	0x31, 0x04, 0x2b, 0x16, 0x6f, 0x19, 0x86, 0x02, 0x0b, 0x30, 0xa0, 0xc9, 0x86, 0x26, 0xed, 0x12,
	0x78, 0xf4, 0xd2, 0x15, 0x1b, 0x30, 0x4f, 0x96, 0x38, 0x45, 0x89, 0x4c, 0xaa, 0xa2, 0xe4, 0x2c,
	0x0f, 0xb4, 0x37, 0xdc, 0x03, 0x0c, 0x3c, 0x4a, 0x96, 0x23, 0x4b, 0x2d, 0x06, 0xec, 0x3f, 0xf1,
	0xee, 0xf8, 0xe1, 0xf7, 0x4e, 0xbc, 0x93, 0xa0, 0x2f, 0x59, 0xb8, 0x60, 0xe1, 0x28, 0x98, 0x8d,
	0x66, 0xc2, 0x77, 0xf7, 0x83, 0x50, 0x44, 0x82, 0xd4, 0xd5, 0xb3, 0xf9, 0x4f, 0x13, 0xda, 0x54,
	0x88, 0xf9, 0x19, 0x93, 0xd2, 0x72, 0x19, 0x79, 0x0b, 0x43, 0x3b, 0x64, 0x56, 0xc4, 0xa6, 0x16,
	0x77, 0xa6, 0x57, 0xc2, 0xe3, 0xd3, 0x50, 0x88, 0xf9, 0x34, 0x64, 0xef, 0x86, 0x95, 0x27, 0x95,
	0xbd, 0xf6, 0xc1, 0xee, 0x3e, 0x42, 0x8e, 0x31, 0xea, 0x05, 0x77, 0x5e, 0x09, 0x8f, 0x2b, 0x02,
	0x65, 0xef, 0x62, 0x26, 0xa3, 0x93, 0x0d, 0xda, 0xb7, 0x0b, 0x7c, 0xe4, 0x37, 0xd8, 0x29, 0x21,
	0xcb, 0x60, 0x58, 0x45, 0xf4, 0xe3, 0x52, 0xb4, 0x0c, 0x04, 0x97, 0xec, 0x64, 0x83, 0x6e, 0xdb,
	0x45, 0x4e, 0x72, 0x08, 0xf7, 0xee, 0x6a, 0xad, 0x21, 0x70, 0x5b, 0x03, 0xd7, 0x25, 0xb6, 0xaf,
	0x56, 0x94, 0x7d, 0x07, 0xdd, 0x9c, 0x9c, 0x3a, 0xee, 0x1e, 0xe4, 0x77, 0x2f, 0x55, 0x74, 0xae,
	0x4a, 0x0f, 0x9f, 0x4b, 0x77, 0xb8, 0x59, 0x74, 0x78, 0x52, 0xe1, 0xd5, 0xc3, 0xcf, 0xa4, 0x4b,
	0xc6, 0xd0, 0xe7, 0x22, 0xf2, 0xfe, 0xbc, 0x9d, 0x86, 0xcc, 0x66, 0xde, 0xc2, 0xe3, 0x2e, 0x26,
	0xd0, 0x40, 0xc6, 0xc7, 0x9a, 0x71, 0x8e, 0x11, 0x34, 0x0d, 0xc8, 0xf2, 0x20, 0x7c, 0xcd, 0x53,
	0x48, 0x54, 0xaa, 0x9a, 0xef, 0x21, 0x66, 0xe2, 0xf2, 0x44, 0xa5, 0xf1, 0x0c, 0x1e, 0xc8, 0x38,
	0x5c, 0x78, 0x0b, 0xcb, 0x57, 0xf5, 0x89, 0xfd, 0x08, 0x81, 0x2d, 0x04, 0x3e, 0xd2, 0xc0, 0x49,
	0x12, 0x40, 0xd1, 0x9f, 0xf1, 0xb6, 0xe4, 0x5d, 0x87, 0x74, 0x55, 0xbd, 0x65, 0x64, 0x85, 0xd1,
	0xd4, 0xb5, 0xe6, 0x0c, 0x93, 0x35, 0x56, 0xeb, 0x3d, 0x51, 0xbe, 0x97, 0xd6, 0x9c, 0x65, 0x69,
	0x76, 0xe4, 0x8a, 0x2d, 0xb7, 0x5f, 0x29, 0x81, 0xc2, 0xfd, 0x99, 0x88, 0x6c, 0xbf, 0x3a, 0xff,
	0x25, 0x6c, 0xc5, 0x81, 0xa3, 0x6e, 0xe2, 0x0d, 0xb3, 0x02, 0xc1, 0x51, 0x42, 0x1b, 0x11, 0x3b,
	0x1a, 0x71, 0x81, 0xee, 0x5f, 0xd0, 0x9b, 0xa9, 0xb8, 0x1f, 0xdf, 0x35, 0x93, 0x57, 0x40, 0xf2,
	0x20, 0x19, 0x0c, 0x3b, 0x48, 0x7a, 0x58, 0x44, 0x5a, 0x5e, 0xa0, 0x5e, 0x9c, 0xb3, 0x93, 0xaf,
	0xc0, 0x08, 0x99, 0xe5, 0xdc, 0xa2, 0x98, 0x7b, 0x88, 0x20, 0x1a, 0x41, 0x95, 0x39, 0x53, 0xd1,
	0x0a, 0x93, 0x75, 0xb6, 0x45, 0x95, 0xa0, 0xbb, 0xb6, 0x25, 0x4b, 0x5f, 0x6f, 0x39, 0x93, 0xee,
	0x51, 0x03, 0xea, 0x8e, 0x15, 0x59, 0xe6, 0x21, 0x0c, 0xcb, 0x1a, 0x98, 0x3c, 0x86, 0x76, 0xe0,
	0x5b, 0xb7, 0x2c, 0x9c, 0x72, 0x6b, 0xce, 0xb0, 0xeb, 0x0d, 0x0a, 0xda, 0x74, 0x6e, 0xcd, 0x99,
	0xf9, 0x13, 0xec, 0x94, 0xb6, 0x28, 0xd9, 0x85, 0xba, 0xea, 0x83, 0x64, 0x58, 0x40, 0xa2, 0x47,
	0x45, 0xa0, 0x9d, 0xf4, 0x61, 0x33, 0x12, 0xd7, 0x8c, 0x63, 0xcb, 0x1b, 0x54, 0x2f, 0xcc, 0xd7,
	0x70, 0x3f, 0x2f, 0xe3, 0x23, 0x68, 0x62, 0x43, 0x79, 0x0e, 0xb2, 0x6a, 0xb4, 0xa1, 0x96, 0xa7,
	0x4e, 0x5e, 0x5f, 0x75, 0x4d, 0xdf, 0x09, 0xf4, 0xfe, 0x27, 0x59, 0xcf, 0x33, 0x59, 0xe9, 0x80,
	0x7c, 0x0a, 0x0d, 0x7d, 0x54, 0x82, 0xea, 0x68, 0xd4, 0x18, 0x6d, 0x34, 0xf1, 0x99, 0xaf, 0x61,
	0x50, 0xdc, 0xb3, 0xe4, 0x11, 0x18, 0x89, 0xfa, 0x65, 0x62, 0x2d, 0x6d, 0x38, 0x75, 0x4a, 0x54,
	0xfc, 0xbe, 0x06, 0xfb, 0x4f, 0x62, 0xc8, 0x2e, 0xc0, 0xb5, 0xe7, 0xfb, 0xba, 0x3a, 0x69, 0xbd,
	0x32, 0x8b, 0x79, 0x0b, 0xdb, 0x85, 0xdd, 0xab, 0xf0, 0x37, 0x1e, 0xe7, 0x65, 0x78, 0xed, 0x23,
	0xdf, 0x82, 0x11, 0xb0, 0x50, 0x0a, 0x6e, 0xf9, 0x72, 0x58, 0x7d, 0x52, 0xcb, 0x86, 0x4c, 0x4a,
	0x1d, 0x27, 0x6e, 0x4d, 0xa7, 0x59, 0xb8, 0xf9, 0x16, 0x06, 0xc5, 0x41, 0x1f, 0xbc, 0x85, 0xe4,
	0x13, 0x9d, 0xd5, 0xd4, 0x16, 0x31, 0x8f, 0x30, 0xab, 0x1a, 0x35, 0x94, 0xe5, 0x58, 0x19, 0xcc,
	0x3d, 0xe8, 0xe5, 0x07, 0x49, 0x56, 0xde, 0xca, 0x6a, 0x79, 0x0f, 0x56, 0x22, 0xd3, 0xcc, 0x3f,
	0x70, 0x5d, 0xcc, 0x63, 0x78, 0x50, 0x30, 0x23, 0xc8, 0x00, 0x1a, 0x56, 0x14, 0x59, 0xf6, 0x75,
	0x7a, 0x65, 0xf5, 0xaa, 0xe4, 0xbd, 0x0e, 0xa0, 0x5f, 0x34, 0x1e, 0xcc, 0xa7, 0xd0, 0x59, 0xed,
	0xf9, 0x12, 0xd9, 0xcf, 0x92, 0xa8, 0x54, 0xf2, 0xfb, 0x2e, 0x96, 0xf9, 0x77, 0x05, 0xea, 0x4a,
	0x3e, 0xe9, 0x42, 0x75, 0xe9, 0xae, 0x7a, 0x0e, 0x79, 0x06, 0x86, 0x9e, 0xc2, 0xb1, 0xaf, 0xaf,
	0x46, 0xf7, 0xa0, 0xab, 0xb3, 0xc5, 0xc2, 0xc5, 0x3e, 0xa3, 0x2d, 0x37, 0x79, 0x22, 0x9f, 0x41,
	0x53, 0x13, 0xe5, 0xb0, 0x86, 0xef, 0xf9, 0xee, 0x85, 0x48, 0x9d, 0xea, 0xd5, 0x20, 0x14, 0xa7,
	0x2e, 0x7e, 0x4c, 0x5b, 0x14, 0x8f, 0xc1, 0x3a, 0x93, 0x1d, 0x68, 0x89, 0x1b, 0xae, 0x85, 0x6e,
	0xa2, 0x92, 0x26, 0xae, 0x4f, 0x1d, 0x93, 0x42, 0x43, 0xc3, 0xd6, 0x84, 0x12, 0xa8, 0xaf, 0xb4,
	0x3b, 0x3e, 0xab, 0x98, 0xcb, 0x00, 0x3f, 0xf5, 0x35, 0x5a, 0xbd, 0x0c, 0x54, 0xa1, 0x70, 0xd2,
	0x25, 0x47, 0xea, 0xc5, 0xe7, 0x9f, 0x42, 0x2b, 0xcd, 0x85, 0x18, 0xb0, 0x79, 0x71, 0x3e, 0xf9,
	0xe1, 0xe7, 0xde, 0x06, 0xe9, 0x40, 0x6b, 0x72, 0x41, 0xdf, 0x9c, 0xbe, 0x79, 0xf1, 0x63, 0xaf,
	0x72, 0xf0, 0x3d, 0xb4, 0x8f, 0x84, 0xef, 0x4e, 0x58, 0xb8, 0xf0, 0x6c, 0x46, 0xbe, 0x81, 0xe6,
	0xb1, 0xe0, 0x9c, 0xd9, 0x11, 0xd9, 0xca, 0x5e, 0x7e, 0x52, 0xea, 0x87, 0xeb, 0x26, 0x73, 0x63,
	0xaf, 0xf2, 0x65, 0xe5, 0xe8, 0x0f, 0x18, 0x8a, 0xd0, 0x45, 0xef, 0xd4, 0x61, 0x0b, 0xe6, 0x0b,
	0x75, 0xd5, 0x71, 0x7d, 0x64, 0x28, 0xfe, 0x58, 0xfd, 0x7a, 0x8d, 0x2b, 0xbf, 0x3e, 0x77, 0xbd,
	0xe8, 0x32, 0x9e, 0xed, 0xdb, 0x62, 0x8e, 0xff, 0x64, 0x5f, 0x64, 0xd1, 0xa3, 0xbf, 0x46, 0x41,
	0x28, 0xae, 0x98, 0x1d, 0x49, 0x74, 0x8d, 0x96, 0x7f, 0x6f, 0x87, 0xc1, 0x6c, 0xd6, 0xc0, 0x9f,
	0xb7, 0xaf, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x25, 0x86, 0xdc, 0xd4, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BolgServiceClient is the client API for BolgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BolgServiceClient interface {
	// ConnectはRoom Messagingを行うためのRPCです。
	Connect(ctx context.Context, opts ...grpc.CallOption) (BolgService_ConnectClient, error)
}

type bolgServiceClient struct {
	cc *grpc.ClientConn
}

func NewBolgServiceClient(cc *grpc.ClientConn) BolgServiceClient {
	return &bolgServiceClient{cc}
}

func (c *bolgServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (BolgService_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BolgService_serviceDesc.Streams[0], "/bolg.BolgService/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &bolgServiceConnectClient{stream}
	return x, nil
}

type BolgService_ConnectClient interface {
	Send(*RoomMessage) error
	Recv() (*RoomMessage, error)
	grpc.ClientStream
}

type bolgServiceConnectClient struct {
	grpc.ClientStream
}

func (x *bolgServiceConnectClient) Send(m *RoomMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bolgServiceConnectClient) Recv() (*RoomMessage, error) {
	m := new(RoomMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BolgServiceServer is the server API for BolgService service.
type BolgServiceServer interface {
	// ConnectはRoom Messagingを行うためのRPCです。
	Connect(BolgService_ConnectServer) error
}

func RegisterBolgServiceServer(s *grpc.Server, srv BolgServiceServer) {
	s.RegisterService(&_BolgService_serviceDesc, srv)
}

func _BolgService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BolgServiceServer).Connect(&bolgServiceConnectServer{stream})
}

type BolgService_ConnectServer interface {
	Send(*RoomMessage) error
	Recv() (*RoomMessage, error)
	grpc.ServerStream
}

type bolgServiceConnectServer struct {
	grpc.ServerStream
}

func (x *bolgServiceConnectServer) Send(m *RoomMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bolgServiceConnectServer) Recv() (*RoomMessage, error) {
	m := new(RoomMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BolgService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bolg.BolgService",
	HandlerType: (*BolgServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _BolgService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server/pb/bolg.proto",
}
