// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/pb/bolg.proto

package org.bolg_developers.bolg;

public final class BolgProto {
  private BolgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bolg_RoomMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bolg_RoomMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bolg_CreateAndJoinRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bolg_CreateAndJoinRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bolg_CreateAndJoinRoomResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bolg_CreateAndJoinRoomResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bolg_Room_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bolg_Room_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bolg_Player_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bolg_Player_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024server/pb/bolg.proto\022\004bolg\032\037google/pro" +
      "tobuf/timestamp.proto\"\237\001\n\013RoomMessage\022B\n" +
      "\030create_and_join_room_req\030\001 \001(\0132\036.bolg.C" +
      "reateAndJoinRoomRequestH\000\022D\n\031create_and_" +
      "join_room_resp\030\002 \001(\0132\037.bolg.CreateAndJoi" +
      "nRoomResponseH\000B\006\n\004data\"/\n\030CreateAndJoin" +
      "RoomRequest\022\023\n\013player_name\030\001 \001(\t\"5\n\031Crea" +
      "teAndJoinRoomResponse\022\030\n\004room\030\001 \001(\0132\n.bo" +
      "lg.Room\"z\n\004Room\022\n\n\002id\030\001 \001(\003\022!\n\tgame_rule" +
      "\030\002 \001(\0162\016.bolg.GameRule\022\035\n\007players\030\003 \003(\0132" +
      "\014.bolg.Player\022\022\n\ngame_start\030\004 \001(\010\022\020\n\010own" +
      "er_id\030\005 \001(\003\"=\n\006Player\022\n\n\002id\030\001 \001(\003\022\014\n\004nam" +
      "e\030\002 \001(\t\022\n\n\002hp\030\003 \001(\003\022\r\n\005ready\030\004 \001(\010*#\n\010Ga" +
      "meRule\022\t\n\005UNSET\020\000\022\014\n\010SURVIVAL\020\0012N\n\013BolgS" +
      "ervice\022?\n\021CreateAndJoinRoom\022\021.bolg.RoomM" +
      "essage\032\021.bolg.RoomMessage\"\000(\0010\001B`\n\030org.b" +
      "olg_developers.bolgB\tBolgProtoP\001Z7github" +
      ".com/bolg-developers/x/projects/bolg/ser" +
      "ver/pb;pbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_bolg_RoomMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bolg_RoomMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bolg_RoomMessage_descriptor,
        new java.lang.String[] { "CreateAndJoinRoomReq", "CreateAndJoinRoomResp", "Data", });
    internal_static_bolg_CreateAndJoinRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bolg_CreateAndJoinRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bolg_CreateAndJoinRoomRequest_descriptor,
        new java.lang.String[] { "PlayerName", });
    internal_static_bolg_CreateAndJoinRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bolg_CreateAndJoinRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bolg_CreateAndJoinRoomResponse_descriptor,
        new java.lang.String[] { "Room", });
    internal_static_bolg_Room_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_bolg_Room_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bolg_Room_descriptor,
        new java.lang.String[] { "Id", "GameRule", "Players", "GameStart", "OwnerId", });
    internal_static_bolg_Player_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_bolg_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bolg_Player_descriptor,
        new java.lang.String[] { "Id", "Name", "Hp", "Ready", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
