// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/pb/bolg.proto

package org.bolg_developers.bolg;

/**
 * Protobuf enum {@code bolg.GameRule}
 */
public enum GameRule
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNSET = 0;</code>
   */
  UNSET(0),
  /**
   * <code>SURVIVAL = 1;</code>
   */
  SURVIVAL(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNSET = 0;</code>
   */
  public static final int UNSET_VALUE = 0;
  /**
   * <code>SURVIVAL = 1;</code>
   */
  public static final int SURVIVAL_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static GameRule valueOf(int value) {
    return forNumber(value);
  }

  public static GameRule forNumber(int value) {
    switch (value) {
      case 0: return UNSET;
      case 1: return SURVIVAL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GameRule>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      GameRule> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GameRule>() {
          public GameRule findValueByNumber(int number) {
            return GameRule.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.bolg_developers.bolg.BolgProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final GameRule[] VALUES = values();

  public static GameRule valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private GameRule(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:bolg.GameRule)
}

