// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/pb/bolg.proto

package org.bolg_developers.bolg;

public interface JoinRoomResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bolg.JoinRoomResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bolg.Room room = 1;</code>
   */
  boolean hasRoom();
  /**
   * <code>.bolg.Room room = 1;</code>
   */
  org.bolg_developers.bolg.Room getRoom();
  /**
   * <code>.bolg.Room room = 1;</code>
   */
  org.bolg_developers.bolg.RoomOrBuilder getRoomOrBuilder();
}
