// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/pb/bolg.proto

package org.bolg_developers.bolg;

public interface JoinRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bolg.JoinRoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 room_id = 1;</code>
   */
  long getRoomId();

  /**
   * <pre>
   * 注意！: このフィールドは認証処理が実装され次第消えます。
   * </pre>
   *
   * <code>string player_name = 2;</code>
   */
  java.lang.String getPlayerName();
  /**
   * <pre>
   * 注意！: このフィールドは認証処理が実装され次第消えます。
   * </pre>
   *
   * <code>string player_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getPlayerNameBytes();
}
