// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/pb/bolg.proto

package org.bolg_developers.bolg;

public interface PlayerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bolg.Player)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * output only
   * idは赤外線信号にも利用されます。
   * </pre>
   *
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <pre>
   * nameはUserのnameと同じです。
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * nameはUserのnameと同じです。
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * output only
   * </pre>
   *
   * <code>int64 hp = 3;</code>
   */
  long getHp();

  /**
   * <pre>
   * output only
   * readyはゲームを行うための準備ができたかどうかを表します。
   * ルーム内のすべてのプレイヤーのreadyがtrueになったとき、
   * ゲームを開始することができます。
   * </pre>
   *
   * <code>bool ready = 4;</code>
   */
  boolean getReady();
}
