// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/pb/bolg.proto

package org.bolg_developers.bolg;

public interface ReadyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bolg.ReadyResponse)
    com.google.protobuf.MessageOrBuilder {
}
