// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/pb/bolg.proto

package org.bolg_developers.bolg;

public interface ReadyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bolg.ReadyMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * player_idは準備完了したプレイヤーのIDです。
   * </pre>
   *
   * <code>int64 player_id = 1;</code>
   */
  long getPlayerId();
}
