// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/pb/bolg.proto

package org.bolg_developers.bolg;

public interface RecoverHPResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bolg.RecoverHPResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bolg.Player player = 1;</code>
   */
  boolean hasPlayer();
  /**
   * <code>.bolg.Player player = 1;</code>
   */
  org.bolg_developers.bolg.Player getPlayer();
  /**
   * <code>.bolg.Player player = 1;</code>
   */
  org.bolg_developers.bolg.PlayerOrBuilder getPlayerOrBuilder();
}
