// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/pb/bolg.proto

package org.bolg_developers.bolg;

/**
 * Protobuf type {@code bolg.Room}
 */
public  final class Room extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bolg.Room)
    RoomOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Room.newBuilder() to construct.
  private Room(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Room() {
    id_ = 0L;
    gameRule_ = 0;
    players_ = java.util.Collections.emptyList();
    gameStart_ = false;
    ownerId_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Room(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            gameRule_ = rawValue;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              players_ = new java.util.ArrayList<org.bolg_developers.bolg.Player>();
              mutable_bitField0_ |= 0x00000004;
            }
            players_.add(
                input.readMessage(org.bolg_developers.bolg.Player.parser(), extensionRegistry));
            break;
          }
          case 32: {

            gameStart_ = input.readBool();
            break;
          }
          case 40: {

            ownerId_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        players_ = java.util.Collections.unmodifiableList(players_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.bolg_developers.bolg.BolgProto.internal_static_bolg_Room_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.bolg_developers.bolg.BolgProto.internal_static_bolg_Room_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.bolg_developers.bolg.Room.class, org.bolg_developers.bolg.Room.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <pre>
   * output only
   * idはルーム番号にも利用されます。
   * </pre>
   *
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int GAME_RULE_FIELD_NUMBER = 2;
  private int gameRule_;
  /**
   * <pre>
   * output only
   * </pre>
   *
   * <code>.bolg.GameRule game_rule = 2;</code>
   */
  public int getGameRuleValue() {
    return gameRule_;
  }
  /**
   * <pre>
   * output only
   * </pre>
   *
   * <code>.bolg.GameRule game_rule = 2;</code>
   */
  public org.bolg_developers.bolg.GameRule getGameRule() {
    org.bolg_developers.bolg.GameRule result = org.bolg_developers.bolg.GameRule.valueOf(gameRule_);
    return result == null ? org.bolg_developers.bolg.GameRule.UNRECOGNIZED : result;
  }

  public static final int PLAYERS_FIELD_NUMBER = 3;
  private java.util.List<org.bolg_developers.bolg.Player> players_;
  /**
   * <pre>
   * output only
   * </pre>
   *
   * <code>repeated .bolg.Player players = 3;</code>
   */
  public java.util.List<org.bolg_developers.bolg.Player> getPlayersList() {
    return players_;
  }
  /**
   * <pre>
   * output only
   * </pre>
   *
   * <code>repeated .bolg.Player players = 3;</code>
   */
  public java.util.List<? extends org.bolg_developers.bolg.PlayerOrBuilder> 
      getPlayersOrBuilderList() {
    return players_;
  }
  /**
   * <pre>
   * output only
   * </pre>
   *
   * <code>repeated .bolg.Player players = 3;</code>
   */
  public int getPlayersCount() {
    return players_.size();
  }
  /**
   * <pre>
   * output only
   * </pre>
   *
   * <code>repeated .bolg.Player players = 3;</code>
   */
  public org.bolg_developers.bolg.Player getPlayers(int index) {
    return players_.get(index);
  }
  /**
   * <pre>
   * output only
   * </pre>
   *
   * <code>repeated .bolg.Player players = 3;</code>
   */
  public org.bolg_developers.bolg.PlayerOrBuilder getPlayersOrBuilder(
      int index) {
    return players_.get(index);
  }

  public static final int GAME_START_FIELD_NUMBER = 4;
  private boolean gameStart_;
  /**
   * <pre>
   * output only
   * </pre>
   *
   * <code>bool game_start = 4;</code>
   */
  public boolean getGameStart() {
    return gameStart_;
  }

  public static final int OWNER_ID_FIELD_NUMBER = 5;
  private long ownerId_;
  /**
   * <pre>
   * output only
   * owner_idはルームオーナーとなるプレイヤーのIDです。
   * 値が0の場合、オーナーが存在しないことを意味します。
   * </pre>
   *
   * <code>int64 owner_id = 5;</code>
   */
  public long getOwnerId() {
    return ownerId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (gameRule_ != org.bolg_developers.bolg.GameRule.UNSET.getNumber()) {
      output.writeEnum(2, gameRule_);
    }
    for (int i = 0; i < players_.size(); i++) {
      output.writeMessage(3, players_.get(i));
    }
    if (gameStart_ != false) {
      output.writeBool(4, gameStart_);
    }
    if (ownerId_ != 0L) {
      output.writeInt64(5, ownerId_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (gameRule_ != org.bolg_developers.bolg.GameRule.UNSET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, gameRule_);
    }
    for (int i = 0; i < players_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, players_.get(i));
    }
    if (gameStart_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, gameStart_);
    }
    if (ownerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, ownerId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.bolg_developers.bolg.Room)) {
      return super.equals(obj);
    }
    org.bolg_developers.bolg.Room other = (org.bolg_developers.bolg.Room) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && gameRule_ == other.gameRule_;
    result = result && getPlayersList()
        .equals(other.getPlayersList());
    result = result && (getGameStart()
        == other.getGameStart());
    result = result && (getOwnerId()
        == other.getOwnerId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + GAME_RULE_FIELD_NUMBER;
    hash = (53 * hash) + gameRule_;
    if (getPlayersCount() > 0) {
      hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getPlayersList().hashCode();
    }
    hash = (37 * hash) + GAME_START_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getGameStart());
    hash = (37 * hash) + OWNER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOwnerId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.bolg_developers.bolg.Room parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.bolg_developers.bolg.Room parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.bolg_developers.bolg.Room parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.bolg_developers.bolg.Room parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.bolg_developers.bolg.Room parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.bolg_developers.bolg.Room parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.bolg_developers.bolg.Room parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.bolg_developers.bolg.Room parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.bolg_developers.bolg.Room parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.bolg_developers.bolg.Room parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.bolg_developers.bolg.Room parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.bolg_developers.bolg.Room parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.bolg_developers.bolg.Room prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bolg.Room}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bolg.Room)
      org.bolg_developers.bolg.RoomOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bolg_developers.bolg.BolgProto.internal_static_bolg_Room_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bolg_developers.bolg.BolgProto.internal_static_bolg_Room_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bolg_developers.bolg.Room.class, org.bolg_developers.bolg.Room.Builder.class);
    }

    // Construct using org.bolg_developers.bolg.Room.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPlayersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      gameRule_ = 0;

      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        playersBuilder_.clear();
      }
      gameStart_ = false;

      ownerId_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.bolg_developers.bolg.BolgProto.internal_static_bolg_Room_descriptor;
    }

    public org.bolg_developers.bolg.Room getDefaultInstanceForType() {
      return org.bolg_developers.bolg.Room.getDefaultInstance();
    }

    public org.bolg_developers.bolg.Room build() {
      org.bolg_developers.bolg.Room result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.bolg_developers.bolg.Room buildPartial() {
      org.bolg_developers.bolg.Room result = new org.bolg_developers.bolg.Room(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.gameRule_ = gameRule_;
      if (playersBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          players_ = java.util.Collections.unmodifiableList(players_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.players_ = players_;
      } else {
        result.players_ = playersBuilder_.build();
      }
      result.gameStart_ = gameStart_;
      result.ownerId_ = ownerId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.bolg_developers.bolg.Room) {
        return mergeFrom((org.bolg_developers.bolg.Room)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.bolg_developers.bolg.Room other) {
      if (other == org.bolg_developers.bolg.Room.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.gameRule_ != 0) {
        setGameRuleValue(other.getGameRuleValue());
      }
      if (playersBuilder_ == null) {
        if (!other.players_.isEmpty()) {
          if (players_.isEmpty()) {
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePlayersIsMutable();
            players_.addAll(other.players_);
          }
          onChanged();
        }
      } else {
        if (!other.players_.isEmpty()) {
          if (playersBuilder_.isEmpty()) {
            playersBuilder_.dispose();
            playersBuilder_ = null;
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000004);
            playersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPlayersFieldBuilder() : null;
          } else {
            playersBuilder_.addAllMessages(other.players_);
          }
        }
      }
      if (other.getGameStart() != false) {
        setGameStart(other.getGameStart());
      }
      if (other.getOwnerId() != 0L) {
        setOwnerId(other.getOwnerId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.bolg_developers.bolg.Room parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.bolg_developers.bolg.Room) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <pre>
     * output only
     * idはルーム番号にも利用されます。
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     * output only
     * idはルーム番号にも利用されます。
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * output only
     * idはルーム番号にも利用されます。
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private int gameRule_ = 0;
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>.bolg.GameRule game_rule = 2;</code>
     */
    public int getGameRuleValue() {
      return gameRule_;
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>.bolg.GameRule game_rule = 2;</code>
     */
    public Builder setGameRuleValue(int value) {
      gameRule_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>.bolg.GameRule game_rule = 2;</code>
     */
    public org.bolg_developers.bolg.GameRule getGameRule() {
      org.bolg_developers.bolg.GameRule result = org.bolg_developers.bolg.GameRule.valueOf(gameRule_);
      return result == null ? org.bolg_developers.bolg.GameRule.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>.bolg.GameRule game_rule = 2;</code>
     */
    public Builder setGameRule(org.bolg_developers.bolg.GameRule value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      gameRule_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>.bolg.GameRule game_rule = 2;</code>
     */
    public Builder clearGameRule() {
      
      gameRule_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<org.bolg_developers.bolg.Player> players_ =
      java.util.Collections.emptyList();
    private void ensurePlayersIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        players_ = new java.util.ArrayList<org.bolg_developers.bolg.Player>(players_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.bolg_developers.bolg.Player, org.bolg_developers.bolg.Player.Builder, org.bolg_developers.bolg.PlayerOrBuilder> playersBuilder_;

    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public java.util.List<org.bolg_developers.bolg.Player> getPlayersList() {
      if (playersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(players_);
      } else {
        return playersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public int getPlayersCount() {
      if (playersBuilder_ == null) {
        return players_.size();
      } else {
        return playersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public org.bolg_developers.bolg.Player getPlayers(int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);
      } else {
        return playersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public Builder setPlayers(
        int index, org.bolg_developers.bolg.Player value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.set(index, value);
        onChanged();
      } else {
        playersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public Builder setPlayers(
        int index, org.bolg_developers.bolg.Player.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.set(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public Builder addPlayers(org.bolg_developers.bolg.Player value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(value);
        onChanged();
      } else {
        playersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public Builder addPlayers(
        int index, org.bolg_developers.bolg.Player value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(index, value);
        onChanged();
      } else {
        playersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public Builder addPlayers(
        org.bolg_developers.bolg.Player.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public Builder addPlayers(
        int index, org.bolg_developers.bolg.Player.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public Builder addAllPlayers(
        java.lang.Iterable<? extends org.bolg_developers.bolg.Player> values) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, players_);
        onChanged();
      } else {
        playersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public Builder clearPlayers() {
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        playersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public Builder removePlayers(int index) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.remove(index);
        onChanged();
      } else {
        playersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public org.bolg_developers.bolg.Player.Builder getPlayersBuilder(
        int index) {
      return getPlayersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public org.bolg_developers.bolg.PlayerOrBuilder getPlayersOrBuilder(
        int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);  } else {
        return playersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public java.util.List<? extends org.bolg_developers.bolg.PlayerOrBuilder> 
         getPlayersOrBuilderList() {
      if (playersBuilder_ != null) {
        return playersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(players_);
      }
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public org.bolg_developers.bolg.Player.Builder addPlayersBuilder() {
      return getPlayersFieldBuilder().addBuilder(
          org.bolg_developers.bolg.Player.getDefaultInstance());
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public org.bolg_developers.bolg.Player.Builder addPlayersBuilder(
        int index) {
      return getPlayersFieldBuilder().addBuilder(
          index, org.bolg_developers.bolg.Player.getDefaultInstance());
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>repeated .bolg.Player players = 3;</code>
     */
    public java.util.List<org.bolg_developers.bolg.Player.Builder> 
         getPlayersBuilderList() {
      return getPlayersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.bolg_developers.bolg.Player, org.bolg_developers.bolg.Player.Builder, org.bolg_developers.bolg.PlayerOrBuilder> 
        getPlayersFieldBuilder() {
      if (playersBuilder_ == null) {
        playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.bolg_developers.bolg.Player, org.bolg_developers.bolg.Player.Builder, org.bolg_developers.bolg.PlayerOrBuilder>(
                players_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        players_ = null;
      }
      return playersBuilder_;
    }

    private boolean gameStart_ ;
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>bool game_start = 4;</code>
     */
    public boolean getGameStart() {
      return gameStart_;
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>bool game_start = 4;</code>
     */
    public Builder setGameStart(boolean value) {
      
      gameStart_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * output only
     * </pre>
     *
     * <code>bool game_start = 4;</code>
     */
    public Builder clearGameStart() {
      
      gameStart_ = false;
      onChanged();
      return this;
    }

    private long ownerId_ ;
    /**
     * <pre>
     * output only
     * owner_idはルームオーナーとなるプレイヤーのIDです。
     * 値が0の場合、オーナーが存在しないことを意味します。
     * </pre>
     *
     * <code>int64 owner_id = 5;</code>
     */
    public long getOwnerId() {
      return ownerId_;
    }
    /**
     * <pre>
     * output only
     * owner_idはルームオーナーとなるプレイヤーのIDです。
     * 値が0の場合、オーナーが存在しないことを意味します。
     * </pre>
     *
     * <code>int64 owner_id = 5;</code>
     */
    public Builder setOwnerId(long value) {
      
      ownerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * output only
     * owner_idはルームオーナーとなるプレイヤーのIDです。
     * 値が0の場合、オーナーが存在しないことを意味します。
     * </pre>
     *
     * <code>int64 owner_id = 5;</code>
     */
    public Builder clearOwnerId() {
      
      ownerId_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bolg.Room)
  }

  // @@protoc_insertion_point(class_scope:bolg.Room)
  private static final org.bolg_developers.bolg.Room DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.bolg_developers.bolg.Room();
  }

  public static org.bolg_developers.bolg.Room getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Room>
      PARSER = new com.google.protobuf.AbstractParser<Room>() {
    public Room parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Room(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Room> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Room> getParserForType() {
    return PARSER;
  }

  public org.bolg_developers.bolg.Room getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

