// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/pb/bolg.proto

package org.bolg_developers.bolg;

public interface RoomMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bolg.RoomMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bolg.CreateAndJoinRoomRequest create_and_join_room_req = 1;</code>
   */
  boolean hasCreateAndJoinRoomReq();
  /**
   * <code>.bolg.CreateAndJoinRoomRequest create_and_join_room_req = 1;</code>
   */
  org.bolg_developers.bolg.CreateAndJoinRoomRequest getCreateAndJoinRoomReq();
  /**
   * <code>.bolg.CreateAndJoinRoomRequest create_and_join_room_req = 1;</code>
   */
  org.bolg_developers.bolg.CreateAndJoinRoomRequestOrBuilder getCreateAndJoinRoomReqOrBuilder();

  /**
   * <code>.bolg.CreateAndJoinRoomResponse create_and_join_room_resp = 2;</code>
   */
  boolean hasCreateAndJoinRoomResp();
  /**
   * <code>.bolg.CreateAndJoinRoomResponse create_and_join_room_resp = 2;</code>
   */
  org.bolg_developers.bolg.CreateAndJoinRoomResponse getCreateAndJoinRoomResp();
  /**
   * <code>.bolg.CreateAndJoinRoomResponse create_and_join_room_resp = 2;</code>
   */
  org.bolg_developers.bolg.CreateAndJoinRoomResponseOrBuilder getCreateAndJoinRoomRespOrBuilder();

  public org.bolg_developers.bolg.RoomMessage.DataCase getDataCase();
}
