// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/pb/bolg.proto

package org.bolg_developers.bolg;

/**
 * Protobuf type {@code bolg.Stamina}
 */
public  final class Stamina extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bolg.Stamina)
    StaminaOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Stamina.newBuilder() to construct.
  private Stamina(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Stamina() {
    idx_ = 0L;
    valid_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Stamina(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            idx_ = input.readInt64();
            break;
          }
          case 16: {

            valid_ = input.readBool();
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (useTime_ != null) {
              subBuilder = useTime_.toBuilder();
            }
            useTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(useTime_);
              useTime_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.bolg_developers.bolg.BolgProto.internal_static_bolg_Stamina_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.bolg_developers.bolg.BolgProto.internal_static_bolg_Stamina_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.bolg_developers.bolg.Stamina.class, org.bolg_developers.bolg.Stamina.Builder.class);
  }

  public static final int IDX_FIELD_NUMBER = 1;
  private long idx_;
  /**
   * <code>int64 idx = 1;</code>
   */
  public long getIdx() {
    return idx_;
  }

  public static final int VALID_FIELD_NUMBER = 2;
  private boolean valid_;
  /**
   * <code>bool valid = 2;</code>
   */
  public boolean getValid() {
    return valid_;
  }

  public static final int USE_TIME_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp useTime_;
  /**
   * <code>.google.protobuf.Timestamp use_time = 3;</code>
   */
  public boolean hasUseTime() {
    return useTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp use_time = 3;</code>
   */
  public com.google.protobuf.Timestamp getUseTime() {
    return useTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : useTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp use_time = 3;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getUseTimeOrBuilder() {
    return getUseTime();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idx_ != 0L) {
      output.writeInt64(1, idx_);
    }
    if (valid_ != false) {
      output.writeBool(2, valid_);
    }
    if (useTime_ != null) {
      output.writeMessage(3, getUseTime());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idx_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, idx_);
    }
    if (valid_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, valid_);
    }
    if (useTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getUseTime());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.bolg_developers.bolg.Stamina)) {
      return super.equals(obj);
    }
    org.bolg_developers.bolg.Stamina other = (org.bolg_developers.bolg.Stamina) obj;

    boolean result = true;
    result = result && (getIdx()
        == other.getIdx());
    result = result && (getValid()
        == other.getValid());
    result = result && (hasUseTime() == other.hasUseTime());
    if (hasUseTime()) {
      result = result && getUseTime()
          .equals(other.getUseTime());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIdx());
    hash = (37 * hash) + VALID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getValid());
    if (hasUseTime()) {
      hash = (37 * hash) + USE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getUseTime().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.bolg_developers.bolg.Stamina parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.bolg_developers.bolg.Stamina parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.bolg_developers.bolg.Stamina parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.bolg_developers.bolg.Stamina parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.bolg_developers.bolg.Stamina parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.bolg_developers.bolg.Stamina parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.bolg_developers.bolg.Stamina parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.bolg_developers.bolg.Stamina parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.bolg_developers.bolg.Stamina parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.bolg_developers.bolg.Stamina parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.bolg_developers.bolg.Stamina parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.bolg_developers.bolg.Stamina parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.bolg_developers.bolg.Stamina prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bolg.Stamina}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bolg.Stamina)
      org.bolg_developers.bolg.StaminaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bolg_developers.bolg.BolgProto.internal_static_bolg_Stamina_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bolg_developers.bolg.BolgProto.internal_static_bolg_Stamina_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bolg_developers.bolg.Stamina.class, org.bolg_developers.bolg.Stamina.Builder.class);
    }

    // Construct using org.bolg_developers.bolg.Stamina.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      idx_ = 0L;

      valid_ = false;

      if (useTimeBuilder_ == null) {
        useTime_ = null;
      } else {
        useTime_ = null;
        useTimeBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.bolg_developers.bolg.BolgProto.internal_static_bolg_Stamina_descriptor;
    }

    public org.bolg_developers.bolg.Stamina getDefaultInstanceForType() {
      return org.bolg_developers.bolg.Stamina.getDefaultInstance();
    }

    public org.bolg_developers.bolg.Stamina build() {
      org.bolg_developers.bolg.Stamina result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.bolg_developers.bolg.Stamina buildPartial() {
      org.bolg_developers.bolg.Stamina result = new org.bolg_developers.bolg.Stamina(this);
      result.idx_ = idx_;
      result.valid_ = valid_;
      if (useTimeBuilder_ == null) {
        result.useTime_ = useTime_;
      } else {
        result.useTime_ = useTimeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.bolg_developers.bolg.Stamina) {
        return mergeFrom((org.bolg_developers.bolg.Stamina)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.bolg_developers.bolg.Stamina other) {
      if (other == org.bolg_developers.bolg.Stamina.getDefaultInstance()) return this;
      if (other.getIdx() != 0L) {
        setIdx(other.getIdx());
      }
      if (other.getValid() != false) {
        setValid(other.getValid());
      }
      if (other.hasUseTime()) {
        mergeUseTime(other.getUseTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.bolg_developers.bolg.Stamina parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.bolg_developers.bolg.Stamina) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long idx_ ;
    /**
     * <code>int64 idx = 1;</code>
     */
    public long getIdx() {
      return idx_;
    }
    /**
     * <code>int64 idx = 1;</code>
     */
    public Builder setIdx(long value) {
      
      idx_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 idx = 1;</code>
     */
    public Builder clearIdx() {
      
      idx_ = 0L;
      onChanged();
      return this;
    }

    private boolean valid_ ;
    /**
     * <code>bool valid = 2;</code>
     */
    public boolean getValid() {
      return valid_;
    }
    /**
     * <code>bool valid = 2;</code>
     */
    public Builder setValid(boolean value) {
      
      valid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool valid = 2;</code>
     */
    public Builder clearValid() {
      
      valid_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp useTime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> useTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp use_time = 3;</code>
     */
    public boolean hasUseTime() {
      return useTimeBuilder_ != null || useTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp use_time = 3;</code>
     */
    public com.google.protobuf.Timestamp getUseTime() {
      if (useTimeBuilder_ == null) {
        return useTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : useTime_;
      } else {
        return useTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp use_time = 3;</code>
     */
    public Builder setUseTime(com.google.protobuf.Timestamp value) {
      if (useTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        useTime_ = value;
        onChanged();
      } else {
        useTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp use_time = 3;</code>
     */
    public Builder setUseTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (useTimeBuilder_ == null) {
        useTime_ = builderForValue.build();
        onChanged();
      } else {
        useTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp use_time = 3;</code>
     */
    public Builder mergeUseTime(com.google.protobuf.Timestamp value) {
      if (useTimeBuilder_ == null) {
        if (useTime_ != null) {
          useTime_ =
            com.google.protobuf.Timestamp.newBuilder(useTime_).mergeFrom(value).buildPartial();
        } else {
          useTime_ = value;
        }
        onChanged();
      } else {
        useTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp use_time = 3;</code>
     */
    public Builder clearUseTime() {
      if (useTimeBuilder_ == null) {
        useTime_ = null;
        onChanged();
      } else {
        useTime_ = null;
        useTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp use_time = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getUseTimeBuilder() {
      
      onChanged();
      return getUseTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp use_time = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUseTimeOrBuilder() {
      if (useTimeBuilder_ != null) {
        return useTimeBuilder_.getMessageOrBuilder();
      } else {
        return useTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : useTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp use_time = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getUseTimeFieldBuilder() {
      if (useTimeBuilder_ == null) {
        useTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUseTime(),
                getParentForChildren(),
                isClean());
        useTime_ = null;
      }
      return useTimeBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bolg.Stamina)
  }

  // @@protoc_insertion_point(class_scope:bolg.Stamina)
  private static final org.bolg_developers.bolg.Stamina DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.bolg_developers.bolg.Stamina();
  }

  public static org.bolg_developers.bolg.Stamina getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Stamina>
      PARSER = new com.google.protobuf.AbstractParser<Stamina>() {
    public Stamina parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Stamina(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Stamina> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Stamina> getParserForType() {
    return PARSER;
  }

  public org.bolg_developers.bolg.Stamina getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

