// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/pb/bolg.proto

package org.bolg_developers.bolg;

public interface StaminaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bolg.Stamina)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * output only
   * </pre>
   *
   * <code>int64 count = 1;</code>
   */
  long getCount();

  /**
   * <pre>
   * output only
   * </pre>
   *
   * <code>int64 max_count = 2;</code>
   */
  long getMaxCount();

  /**
   * <pre>
   * output only
   * recovery_time は「この時間になれば回復する」という時間unix時間を表します。
   * recovery_time 以降に Stamina リソースを取得すると自動的に回復します。
   * ただし count == 0 の状態でスタミナを取得しても自動的には回復しません（代わりにエラーが返されます）。
   * また count == max_count の場合、recovery_time は 0 になります。
   * </pre>
   *
   * <code>int64 recovery_time = 3;</code>
   */
  long getRecoveryTime();
}
