// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/pb/bolg.proto

package org.bolg_developers.bolg;

/**
 * Protobuf type {@code bolg.User}
 */
public  final class User extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bolg.User)
    UserOrBuilder {
private static final long serialVersionUID = 0L;
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private User() {
    name_ = "";
    staminas_ = java.util.Collections.emptyList();
    items_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private User(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              staminas_ = new java.util.ArrayList<org.bolg_developers.bolg.Stamina>();
              mutable_bitField0_ |= 0x00000002;
            }
            staminas_.add(
                input.readMessage(org.bolg_developers.bolg.Stamina.parser(), extensionRegistry));
            break;
          }
          case 24: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              items_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000004;
            }
            items_.add(rawValue);
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                items_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              items_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        staminas_ = java.util.Collections.unmodifiableList(staminas_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.bolg_developers.bolg.BolgProto.internal_static_bolg_User_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.bolg_developers.bolg.BolgProto.internal_static_bolg_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.bolg_developers.bolg.User.class, org.bolg_developers.bolg.User.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STAMINAS_FIELD_NUMBER = 2;
  private java.util.List<org.bolg_developers.bolg.Stamina> staminas_;
  /**
   * <code>repeated .bolg.Stamina staminas = 2;</code>
   */
  public java.util.List<org.bolg_developers.bolg.Stamina> getStaminasList() {
    return staminas_;
  }
  /**
   * <code>repeated .bolg.Stamina staminas = 2;</code>
   */
  public java.util.List<? extends org.bolg_developers.bolg.StaminaOrBuilder> 
      getStaminasOrBuilderList() {
    return staminas_;
  }
  /**
   * <code>repeated .bolg.Stamina staminas = 2;</code>
   */
  public int getStaminasCount() {
    return staminas_.size();
  }
  /**
   * <code>repeated .bolg.Stamina staminas = 2;</code>
   */
  public org.bolg_developers.bolg.Stamina getStaminas(int index) {
    return staminas_.get(index);
  }
  /**
   * <code>repeated .bolg.Stamina staminas = 2;</code>
   */
  public org.bolg_developers.bolg.StaminaOrBuilder getStaminasOrBuilder(
      int index) {
    return staminas_.get(index);
  }

  public static final int ITEMS_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Integer> items_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, org.bolg_developers.bolg.Item> items_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, org.bolg_developers.bolg.Item>() {
            public org.bolg_developers.bolg.Item convert(java.lang.Integer from) {
              org.bolg_developers.bolg.Item result = org.bolg_developers.bolg.Item.valueOf(from);
              return result == null ? org.bolg_developers.bolg.Item.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .bolg.Item items = 3;</code>
   */
  public java.util.List<org.bolg_developers.bolg.Item> getItemsList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, org.bolg_developers.bolg.Item>(items_, items_converter_);
  }
  /**
   * <code>repeated .bolg.Item items = 3;</code>
   */
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .bolg.Item items = 3;</code>
   */
  public org.bolg_developers.bolg.Item getItems(int index) {
    return items_converter_.convert(items_.get(index));
  }
  /**
   * <code>repeated .bolg.Item items = 3;</code>
   */
  public java.util.List<java.lang.Integer>
  getItemsValueList() {
    return items_;
  }
  /**
   * <code>repeated .bolg.Item items = 3;</code>
   */
  public int getItemsValue(int index) {
    return items_.get(index);
  }
  private int itemsMemoizedSerializedSize;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    for (int i = 0; i < staminas_.size(); i++) {
      output.writeMessage(2, staminas_.get(i));
    }
    if (getItemsList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(itemsMemoizedSerializedSize);
    }
    for (int i = 0; i < items_.size(); i++) {
      output.writeEnumNoTag(items_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    for (int i = 0; i < staminas_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, staminas_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < items_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(items_.get(i));
      }
      size += dataSize;
      if (!getItemsList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }itemsMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.bolg_developers.bolg.User)) {
      return super.equals(obj);
    }
    org.bolg_developers.bolg.User other = (org.bolg_developers.bolg.User) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getStaminasList()
        .equals(other.getStaminasList());
    result = result && items_.equals(other.items_);
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getStaminasCount() > 0) {
      hash = (37 * hash) + STAMINAS_FIELD_NUMBER;
      hash = (53 * hash) + getStaminasList().hashCode();
    }
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + items_.hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.bolg_developers.bolg.User parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.bolg_developers.bolg.User parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.bolg_developers.bolg.User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.bolg_developers.bolg.User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.bolg_developers.bolg.User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.bolg_developers.bolg.User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.bolg_developers.bolg.User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.bolg_developers.bolg.User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.bolg_developers.bolg.User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.bolg_developers.bolg.User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.bolg_developers.bolg.User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.bolg_developers.bolg.User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.bolg_developers.bolg.User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bolg.User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bolg.User)
      org.bolg_developers.bolg.UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bolg_developers.bolg.BolgProto.internal_static_bolg_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bolg_developers.bolg.BolgProto.internal_static_bolg_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bolg_developers.bolg.User.class, org.bolg_developers.bolg.User.Builder.class);
    }

    // Construct using org.bolg_developers.bolg.User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStaminasFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      if (staminasBuilder_ == null) {
        staminas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        staminasBuilder_.clear();
      }
      items_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.bolg_developers.bolg.BolgProto.internal_static_bolg_User_descriptor;
    }

    public org.bolg_developers.bolg.User getDefaultInstanceForType() {
      return org.bolg_developers.bolg.User.getDefaultInstance();
    }

    public org.bolg_developers.bolg.User build() {
      org.bolg_developers.bolg.User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.bolg_developers.bolg.User buildPartial() {
      org.bolg_developers.bolg.User result = new org.bolg_developers.bolg.User(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      if (staminasBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          staminas_ = java.util.Collections.unmodifiableList(staminas_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.staminas_ = staminas_;
      } else {
        result.staminas_ = staminasBuilder_.build();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        items_ = java.util.Collections.unmodifiableList(items_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.items_ = items_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.bolg_developers.bolg.User) {
        return mergeFrom((org.bolg_developers.bolg.User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.bolg_developers.bolg.User other) {
      if (other == org.bolg_developers.bolg.User.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (staminasBuilder_ == null) {
        if (!other.staminas_.isEmpty()) {
          if (staminas_.isEmpty()) {
            staminas_ = other.staminas_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureStaminasIsMutable();
            staminas_.addAll(other.staminas_);
          }
          onChanged();
        }
      } else {
        if (!other.staminas_.isEmpty()) {
          if (staminasBuilder_.isEmpty()) {
            staminasBuilder_.dispose();
            staminasBuilder_ = null;
            staminas_ = other.staminas_;
            bitField0_ = (bitField0_ & ~0x00000002);
            staminasBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStaminasFieldBuilder() : null;
          } else {
            staminasBuilder_.addAllMessages(other.staminas_);
          }
        }
      }
      if (!other.items_.isEmpty()) {
        if (items_.isEmpty()) {
          items_ = other.items_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureItemsIsMutable();
          items_.addAll(other.items_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.bolg_developers.bolg.User parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.bolg_developers.bolg.User) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.bolg_developers.bolg.Stamina> staminas_ =
      java.util.Collections.emptyList();
    private void ensureStaminasIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        staminas_ = new java.util.ArrayList<org.bolg_developers.bolg.Stamina>(staminas_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.bolg_developers.bolg.Stamina, org.bolg_developers.bolg.Stamina.Builder, org.bolg_developers.bolg.StaminaOrBuilder> staminasBuilder_;

    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public java.util.List<org.bolg_developers.bolg.Stamina> getStaminasList() {
      if (staminasBuilder_ == null) {
        return java.util.Collections.unmodifiableList(staminas_);
      } else {
        return staminasBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public int getStaminasCount() {
      if (staminasBuilder_ == null) {
        return staminas_.size();
      } else {
        return staminasBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public org.bolg_developers.bolg.Stamina getStaminas(int index) {
      if (staminasBuilder_ == null) {
        return staminas_.get(index);
      } else {
        return staminasBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public Builder setStaminas(
        int index, org.bolg_developers.bolg.Stamina value) {
      if (staminasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStaminasIsMutable();
        staminas_.set(index, value);
        onChanged();
      } else {
        staminasBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public Builder setStaminas(
        int index, org.bolg_developers.bolg.Stamina.Builder builderForValue) {
      if (staminasBuilder_ == null) {
        ensureStaminasIsMutable();
        staminas_.set(index, builderForValue.build());
        onChanged();
      } else {
        staminasBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public Builder addStaminas(org.bolg_developers.bolg.Stamina value) {
      if (staminasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStaminasIsMutable();
        staminas_.add(value);
        onChanged();
      } else {
        staminasBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public Builder addStaminas(
        int index, org.bolg_developers.bolg.Stamina value) {
      if (staminasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStaminasIsMutable();
        staminas_.add(index, value);
        onChanged();
      } else {
        staminasBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public Builder addStaminas(
        org.bolg_developers.bolg.Stamina.Builder builderForValue) {
      if (staminasBuilder_ == null) {
        ensureStaminasIsMutable();
        staminas_.add(builderForValue.build());
        onChanged();
      } else {
        staminasBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public Builder addStaminas(
        int index, org.bolg_developers.bolg.Stamina.Builder builderForValue) {
      if (staminasBuilder_ == null) {
        ensureStaminasIsMutable();
        staminas_.add(index, builderForValue.build());
        onChanged();
      } else {
        staminasBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public Builder addAllStaminas(
        java.lang.Iterable<? extends org.bolg_developers.bolg.Stamina> values) {
      if (staminasBuilder_ == null) {
        ensureStaminasIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, staminas_);
        onChanged();
      } else {
        staminasBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public Builder clearStaminas() {
      if (staminasBuilder_ == null) {
        staminas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        staminasBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public Builder removeStaminas(int index) {
      if (staminasBuilder_ == null) {
        ensureStaminasIsMutable();
        staminas_.remove(index);
        onChanged();
      } else {
        staminasBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public org.bolg_developers.bolg.Stamina.Builder getStaminasBuilder(
        int index) {
      return getStaminasFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public org.bolg_developers.bolg.StaminaOrBuilder getStaminasOrBuilder(
        int index) {
      if (staminasBuilder_ == null) {
        return staminas_.get(index);  } else {
        return staminasBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public java.util.List<? extends org.bolg_developers.bolg.StaminaOrBuilder> 
         getStaminasOrBuilderList() {
      if (staminasBuilder_ != null) {
        return staminasBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(staminas_);
      }
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public org.bolg_developers.bolg.Stamina.Builder addStaminasBuilder() {
      return getStaminasFieldBuilder().addBuilder(
          org.bolg_developers.bolg.Stamina.getDefaultInstance());
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public org.bolg_developers.bolg.Stamina.Builder addStaminasBuilder(
        int index) {
      return getStaminasFieldBuilder().addBuilder(
          index, org.bolg_developers.bolg.Stamina.getDefaultInstance());
    }
    /**
     * <code>repeated .bolg.Stamina staminas = 2;</code>
     */
    public java.util.List<org.bolg_developers.bolg.Stamina.Builder> 
         getStaminasBuilderList() {
      return getStaminasFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.bolg_developers.bolg.Stamina, org.bolg_developers.bolg.Stamina.Builder, org.bolg_developers.bolg.StaminaOrBuilder> 
        getStaminasFieldBuilder() {
      if (staminasBuilder_ == null) {
        staminasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.bolg_developers.bolg.Stamina, org.bolg_developers.bolg.Stamina.Builder, org.bolg_developers.bolg.StaminaOrBuilder>(
                staminas_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        staminas_ = null;
      }
      return staminasBuilder_;
    }

    private java.util.List<java.lang.Integer> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        items_ = new java.util.ArrayList<java.lang.Integer>(items_);
        bitField0_ |= 0x00000004;
      }
    }
    /**
     * <code>repeated .bolg.Item items = 3;</code>
     */
    public java.util.List<org.bolg_developers.bolg.Item> getItemsList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, org.bolg_developers.bolg.Item>(items_, items_converter_);
    }
    /**
     * <code>repeated .bolg.Item items = 3;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .bolg.Item items = 3;</code>
     */
    public org.bolg_developers.bolg.Item getItems(int index) {
      return items_converter_.convert(items_.get(index));
    }
    /**
     * <code>repeated .bolg.Item items = 3;</code>
     */
    public Builder setItems(
        int index, org.bolg_developers.bolg.Item value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemsIsMutable();
      items_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .bolg.Item items = 3;</code>
     */
    public Builder addItems(org.bolg_developers.bolg.Item value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemsIsMutable();
      items_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .bolg.Item items = 3;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends org.bolg_developers.bolg.Item> values) {
      ensureItemsIsMutable();
      for (org.bolg_developers.bolg.Item value : values) {
        items_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .bolg.Item items = 3;</code>
     */
    public Builder clearItems() {
      items_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .bolg.Item items = 3;</code>
     */
    public java.util.List<java.lang.Integer>
    getItemsValueList() {
      return java.util.Collections.unmodifiableList(items_);
    }
    /**
     * <code>repeated .bolg.Item items = 3;</code>
     */
    public int getItemsValue(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .bolg.Item items = 3;</code>
     */
    public Builder setItemsValue(
        int index, int value) {
      ensureItemsIsMutable();
      items_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .bolg.Item items = 3;</code>
     */
    public Builder addItemsValue(int value) {
      ensureItemsIsMutable();
      items_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .bolg.Item items = 3;</code>
     */
    public Builder addAllItemsValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureItemsIsMutable();
      for (int value : values) {
        items_.add(value);
      }
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bolg.User)
  }

  // @@protoc_insertion_point(class_scope:bolg.User)
  private static final org.bolg_developers.bolg.User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.bolg_developers.bolg.User();
  }

  public static org.bolg_developers.bolg.User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new User(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  public org.bolg_developers.bolg.User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

