// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/pb/bolg.proto

package org.bolg_developers.bolg;

public interface UseStaminaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bolg.UseStaminaRequest)
    com.google.protobuf.MessageOrBuilder {
}
