// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/bolgchat/room.proto

package bolgchat

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRoomRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomRequest) Reset()         { *m = CreateRoomRequest{} }
func (m *CreateRoomRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoomRequest) ProtoMessage()    {}
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_efab0eacdcddaa17, []int{0}
}

func (m *CreateRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomRequest.Unmarshal(m, b)
}
func (m *CreateRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomRequest.Merge(m, src)
}
func (m *CreateRoomRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoomRequest.Size(m)
}
func (m *CreateRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomRequest proto.InternalMessageInfo

type CreateRoomResponse struct {
	Room *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	// このルームの誰であるかということを認可するためのJWT。
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomResponse) Reset()         { *m = CreateRoomResponse{} }
func (m *CreateRoomResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRoomResponse) ProtoMessage()    {}
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efab0eacdcddaa17, []int{1}
}

func (m *CreateRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomResponse.Unmarshal(m, b)
}
func (m *CreateRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomResponse.Marshal(b, m, deterministic)
}
func (m *CreateRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomResponse.Merge(m, src)
}
func (m *CreateRoomResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRoomResponse.Size(m)
}
func (m *CreateRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomResponse proto.InternalMessageInfo

func (m *CreateRoomResponse) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *CreateRoomResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type JoinRoomRequest struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Person               *Person  `protobuf:"bytes,2,opt,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomRequest) Reset()         { *m = JoinRoomRequest{} }
func (m *JoinRoomRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRoomRequest) ProtoMessage()    {}
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_efab0eacdcddaa17, []int{2}
}

func (m *JoinRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomRequest.Unmarshal(m, b)
}
func (m *JoinRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomRequest.Marshal(b, m, deterministic)
}
func (m *JoinRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomRequest.Merge(m, src)
}
func (m *JoinRoomRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRoomRequest.Size(m)
}
func (m *JoinRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomRequest proto.InternalMessageInfo

func (m *JoinRoomRequest) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *JoinRoomRequest) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type JoinRoomResponse struct {
	Room *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	// このルームの誰であるかということを認可するためのJWT。
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomResponse) Reset()         { *m = JoinRoomResponse{} }
func (m *JoinRoomResponse) String() string { return proto.CompactTextString(m) }
func (*JoinRoomResponse) ProtoMessage()    {}
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efab0eacdcddaa17, []int{3}
}

func (m *JoinRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomResponse.Unmarshal(m, b)
}
func (m *JoinRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomResponse.Marshal(b, m, deterministic)
}
func (m *JoinRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomResponse.Merge(m, src)
}
func (m *JoinRoomResponse) XXX_Size() int {
	return xxx_messageInfo_JoinRoomResponse.Size(m)
}
func (m *JoinRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomResponse proto.InternalMessageInfo

func (m *JoinRoomResponse) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *JoinRoomResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Person struct {
	// this field is output only.
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_efab0eacdcddaa17, []int{4}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type Room struct {
	// this field is output only.
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Person               []*Person `protobuf:"bytes,2,rep,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_efab0eacdcddaa17, []int{5}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Room) GetPerson() []*Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRoomRequest)(nil), "bolgchat.CreateRoomRequest")
	proto.RegisterType((*CreateRoomResponse)(nil), "bolgchat.CreateRoomResponse")
	proto.RegisterType((*JoinRoomRequest)(nil), "bolgchat.JoinRoomRequest")
	proto.RegisterType((*JoinRoomResponse)(nil), "bolgchat.JoinRoomResponse")
	proto.RegisterType((*Person)(nil), "bolgchat.Person")
	proto.RegisterType((*Room)(nil), "bolgchat.Room")
}

func init() { proto.RegisterFile("api/bolgchat/room.proto", fileDescriptor_efab0eacdcddaa17) }

var fileDescriptor_efab0eacdcddaa17 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x41, 0x4f, 0xea, 0x40,
	0x10, 0xc7, 0x53, 0xe0, 0xf5, 0xc1, 0xf4, 0x85, 0x87, 0xab, 0x09, 0x88, 0x26, 0x62, 0x4f, 0x5c,
	0x6c, 0x03, 0xde, 0xe4, 0xa2, 0x78, 0x30, 0x1a, 0x43, 0x48, 0xf5, 0xe4, 0x85, 0x14, 0x3a, 0x29,
	0xab, 0xb4, 0x53, 0xdb, 0xd2, 0xe8, 0x47, 0xf1, 0xdb, 0x9a, 0xdd, 0xb6, 0x2e, 0x11, 0xe2, 0xc5,
	0xdb, 0xee, 0xfc, 0xe7, 0xff, 0x9b, 0xd9, 0x9d, 0x81, 0xb6, 0x1b, 0x71, 0x7b, 0x4e, 0x2b, 0x7f,
	0xb1, 0x74, 0x53, 0x3b, 0x26, 0x0a, 0xac, 0x28, 0xa6, 0x94, 0x58, 0xbd, 0x0c, 0x9a, 0xfb, 0xb0,
	0x77, 0x1d, 0xa3, 0x9b, 0xa2, 0x43, 0x14, 0x38, 0xf8, 0xba, 0xc6, 0x24, 0x35, 0x27, 0xc0, 0x36,
	0x83, 0x49, 0x44, 0x61, 0x82, 0xcc, 0x84, 0x9a, 0x40, 0x74, 0xb4, 0x9e, 0xd6, 0x37, 0x86, 0x4d,
	0xab, 0x64, 0x58, 0x32, 0x4b, 0x6a, 0xec, 0x00, 0xfe, 0xa4, 0xf4, 0x82, 0x61, 0xa7, 0xd2, 0xd3,
	0xfa, 0x0d, 0x27, 0xbf, 0x98, 0x8f, 0xf0, 0xff, 0x8e, 0x78, 0xb8, 0x51, 0x82, 0xb5, 0xe1, 0xaf,
	0x30, 0xcc, 0xb8, 0x27, 0x79, 0x55, 0x47, 0x17, 0xd7, 0x5b, 0x8f, 0xf5, 0x41, 0x8f, 0x30, 0x4e,
	0x28, 0x47, 0x18, 0xc3, 0x96, 0xaa, 0x33, 0x95, 0x71, 0xa7, 0xd0, 0xcd, 0x7b, 0x68, 0x29, 0xea,
	0xaf, 0x7b, 0x1c, 0x81, 0x9e, 0xf3, 0x59, 0x13, 0x2a, 0x5f, 0x5d, 0x55, 0xb8, 0xc7, 0x4e, 0xe1,
	0x9f, 0xc7, 0x93, 0x68, 0xe5, 0xbe, 0xcf, 0x42, 0x37, 0xc0, 0xc2, 0x66, 0x14, 0xb1, 0x89, 0x1b,
	0xa0, 0x79, 0x09, 0x35, 0x51, 0x60, 0xcb, 0xba, 0xf9, 0x98, 0xea, 0x4f, 0x8f, 0x19, 0x7e, 0x68,
	0x60, 0x08, 0xc4, 0x03, 0xc6, 0x19, 0x5f, 0x20, 0xbb, 0x01, 0x50, 0x23, 0x60, 0x47, 0xca, 0xb7,
	0x35, 0xad, 0xee, 0xf1, 0x6e, 0xb1, 0xf8, 0x91, 0x2b, 0xa8, 0x97, 0xbf, 0xc4, 0x0e, 0x55, 0xe6,
	0xb7, 0x79, 0x74, 0xbb, 0xbb, 0xa4, 0x1c, 0x31, 0x7e, 0x86, 0x13, 0x8a, 0x7d, 0x99, 0x30, 0xf3,
	0x30, 0xc3, 0x15, 0x89, 0xa6, 0x95, 0x21, 0x1b, 0x8c, 0x1b, 0xc2, 0x30, 0x15, 0xbb, 0x35, 0xd5,
	0x9e, 0x2e, 0x7c, 0x9e, 0x2e, 0xd7, 0x73, 0x6b, 0x41, 0x81, 0xdc, 0xbe, 0x33, 0x65, 0xb2, 0xdf,
	0x6c, 0x1f, 0x43, 0xb9, 0x84, 0x6a, 0x31, 0xb3, 0xc1, 0xa8, 0x3c, 0xcf, 0x75, 0xa9, 0x9d, 0x7f,
	0x06, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xe8, 0xe2, 0xd6, 0xbb, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoomServiceClient is the client API for RoomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoomServiceClient interface {
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error)
	JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error)
}

type roomServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoomServiceClient(cc *grpc.ClientConn) RoomServiceClient {
	return &roomServiceClient{cc}
}

func (c *roomServiceClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error) {
	out := new(CreateRoomResponse)
	err := c.cc.Invoke(ctx, "/bolgchat.RoomService/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error) {
	out := new(JoinRoomResponse)
	err := c.cc.Invoke(ctx, "/bolgchat.RoomService/JoinRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomServiceServer is the server API for RoomService service.
type RoomServiceServer interface {
	CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error)
	JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error)
}

func RegisterRoomServiceServer(s *grpc.Server, srv RoomServiceServer) {
	s.RegisterService(&_RoomService_serviceDesc, srv)
}

func _RoomService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bolgchat.RoomService/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bolgchat.RoomService/JoinRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).JoinRoom(ctx, req.(*JoinRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoomService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bolgchat.RoomService",
	HandlerType: (*RoomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _RoomService_CreateRoom_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _RoomService_JoinRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/bolgchat/room.proto",
}
